using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using NUnit.Framework;
using Volleyball.Career.Domain;
using Volleyball.Career.Persistence;
using Volleyball.Shared.Contracts;

namespace Volleyball.Career.EditModeTests
{
    public sealed class CareerSaveJsonCodecTests
    {
        private const long MaximumIJsonSafeInteger = 9007199254740991L;
        private const string UnsupportedV1GoldenHash =
            "d9e9464b0eeeea3c848efff9522e2d41e3c14db40de2c7db40b2daaa5378d237";
        private const string V2GoldenHash = "1aca2541cd552b54e9e7c5c213e2aac35ee18efbe2700a3ffba1b8463f51e39b";
        private const string V2GoldenBase64 =
            "eyJ2ZXJzaW9ucyI6eyJzY2hlbWFWZXJzaW9uIjoyLCJjb250ZW50VmVyc2lvbiI6MSwicnVsZXNldFZlcnNpb24iOjEsImNvbnRyYWN0VmVyc2lvbiI6Miwi" +
            "Y2FyZWVyUmFuZG9tQWxnb3JpdGhtVmVyc2lvbiI6MX0sImlkZW50aXR5Ijp7InByb2ZpbGVJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAw" +
            "MDAwMSIsInNhdmVJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMiIsImxpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAw" +
            "LTAwMDAwMDAwMDAwMyIsInJldmlzaW9uIjoxLCJyZXN0b3JlZEZyb21WZXJzaW9uVG9rZW4iOm51bGwsImNyZWF0ZWRBdFV0Y01zIjowLCJ1cGRhdGVkQXRV" +
            "dGNNcyI6OTAwNzE5OTI1NDc0MDk5MX0sImludGVncml0eSI6eyJzbmFwc2hvdEhhc2giOiIxYWNhMjU0MWNkNTUyYjU0ZTllN2M1YzIxM2UyYWFjMzVlZTE4" +
            "ZWZiZTI3MDBhM2ZmYmExYjg0NjNmNTFlMzliIn0sImNhcmVlclNlZWQiOiIwMDAxMDIwMzA0MDUwNjA3MDgwOTBhMGIwYzBkMGUwZjEwMTExMjEzMTQxNTE2" +
            "MTcxODE5MWExYjFjMWQxZTFmIiwiY2FyZWVyTmFtZSI6IkVzY2FwZXM6XCJcXC8gQ29udHJvbHM6XHUwMDAwXHUwMDAxXHUwMDAyXHUwMDAzXHUwMDA0XHUw" +
            "MDA1XHUwMDA2XHUwMDA3XGJcdFxuXHUwMDBiXGZcclx1MDAwZVx1MDAwZlx1MDAxMFx1MDAxMVx1MDAxMlx1MDAxM1x1MDAxNFx1MDAxNVx1MDAxNlx1MDAx" +
            "N1x1MDAxOFx1MDAxOVx1MDAxYVx1MDAxYlx1MDAxY1x1MDAxZFx1MDAxZVx1MDAxZiBVbmljb2RlOumbqvCfmIAgw6kgZcyBIiwicGxheWVyRHJhZnQiOnsi" +
            "cGxheWVySWQiOiJwbGF5ZXIuYWxwaGEiLCJkaXNwbGF5TmFtZSI6IlBsYXllciDpm6rwn5iAIiwiamVyc2V5TnVtYmVyIjoxMn0sIm9uYm9hcmRpbmciOnsi" +
            "c3RhZ2VzIjpbeyJzdGFnZU51bWJlciI6MSwib2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTAxIiwicmFuZG9tVmVy" +
            "c2lvbiI6MSwiY2hvaWNlSWQiOm51bGwsInJlc29sdmVkT3V0cHV0cyI6W119LHsic3RhZ2VOdW1iZXIiOjIsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAw" +
            "MDAtMDAwMC0wMDAwLTAwMDAwMDAwMDEwMiIsInJhbmRvbVZlcnNpb24iOjEsImNob2ljZUlkIjpudWxsLCJyZXNvbHZlZE91dHB1dHMiOltdfSx7InN0YWdl" +
            "TnVtYmVyIjozLCJvY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDMiLCJyYW5kb21WZXJzaW9uIjoxLCJjaG9pY2VJ" +
            "ZCI6bnVsbCwicmVzb2x2ZWRPdXRwdXRzIjpbXX1dLCJuZXh0U3RhZ2VOdW1iZXIiOjEsImlzRm9ybWFsbHlFbnJvbGxlZCI6ZmFsc2V9LCJwcm9ncmVzc2lv" +
            "biI6eyJraW5kIjoiY2FyZWVyX2NyZWF0ZWQiLCJwaGFzZSI6InVuaXZlcnNpdHkiLCJ0cnlvdXRTdGFnZSI6MCwid2Vla1BsYW4iOm51bGwsIm5leHRTbG90" +
            "TnVtYmVyIjowLCJwZW5kaW5nRXZlbnQiOm51bGwsIm1hdGNoU2Vzc2lvbklkIjpudWxsfSwidHJhaW5pbmdFbXBoYXNlcyI6W10sInBlbmRpbmdNYXRjaCI6" +
            "bnVsbCwicGxheWVyIjpudWxsLCJ0ZWFtSWQiOm51bGwsInBvdGVudGlhbEdyYWRlIjpudWxsLCJmYXRpZ3VlIjpudWxsLCJtaW5kc2V0IjpudWxsLCJjb2Fj" +
            "aFRydXN0IjpudWxsLCJtYXRjaEhpc3RvcnkiOltdLCJvcGVyYXRpb25SZWNlaXB0cyI6W3sib3BlcmF0aW9uSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAw" +
            "MC0wMDAwMDAwMDAyMDAiLCJvcGVyYXRpb25LaW5kIjoiY3JlYXRlX2NhcmVlciIsInRhcmdldCI6eyJ0cnlvdXRTdGFnZSI6MCwidHJ5b3V0T2NjdXJyZW5j" +
            "ZUlkIjpudWxsLCJjaG9pY2VJZCI6bnVsbCwid2Vla1BsYW5JZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51bGws" +
            "ImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsInNjaGVkdWxlSXRlbUlkIjpudWxsLCJjb250" +
            "ZXh0SGFzaCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh" +
            "YWFhYWFhYWFhIiwiYXBwbGllZExpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6MSwi" +
            "Y29tcGxldGVkQXRVdGNNcyI6OTAwNzE5OTI1NDc0MDk5MSwib3V0Y29tZUtpbmQiOiJjYXJlZXJfY3JlYXRlZCIsIm91dGNvbWVTdW1tYXJ5Ijp7InRyeW91" +
            "dFJlc29sdmVkT3V0cHV0cyI6W10sImdyb3d0aEV4cGVyaWVuY2VEZWx0YSI6bnVsbCwiZmF0aWd1ZURlbHRhIjpudWxsLCJtaW5kc2V0RGVsdGEiOm51bGws" +
            "ImNvYWNoVHJ1c3REZWx0YSI6bnVsbCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsImNvbnRleHRIYXNoIjpudWxsfX1dLCJzZXR0bGVtZW50UmVjZWlwdHMiOltd" +
            "fQ==";
        private const string LifecycleGoldenHash = "d26e89d5312a670c6550a54e772af340033d284cbf14c1505c3326c7ff17e984";
        private const string LifecycleGoldenBase64 =
            "eyJ2ZXJzaW9ucyI6eyJzY2hlbWFWZXJzaW9uIjoyLCJjb250ZW50VmVyc2lvbiI6MSwicnVsZXNldFZlcnNpb24iOjEsImNvbnRyYWN0VmVyc2lvbiI6Miwi" +
            "Y2FyZWVyUmFuZG9tQWxnb3JpdGhtVmVyc2lvbiI6MX0sImlkZW50aXR5Ijp7InByb2ZpbGVJZCI6IjExMTExMTExLTExMTEtMTExMS0xMTExLTExMTExMTEx" +
            "MTExMSIsInNhdmVJZCI6IjIyMjIyMjIyLTIyMjItMjIyMi0yMjIyLTIyMjIyMjIyMjIyMiIsImxpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMz" +
            "LTMzMzMzMzMzMzMzMyIsInJldmlzaW9uIjo5LCJyZXN0b3JlZEZyb21WZXJzaW9uVG9rZW4iOm51bGwsImNyZWF0ZWRBdFV0Y01zIjowLCJ1cGRhdGVkQXRV" +
            "dGNNcyI6MTV9LCJpbnRlZ3JpdHkiOnsic25hcHNob3RIYXNoIjoiZDI2ZTg5ZDUzMTJhNjcwYzY1NTBhNTRlNzcyYWYzNDAwMzNkMjg0Y2JmMTRjMTUwNWMz" +
            "MzI2YzdmZjE3ZTk4NCJ9LCJjYXJlZXJTZWVkIjoiMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw" +
            "MDAwMCIsImNhcmVlck5hbWUiOiJMaWZlY3ljbGUgR29sZGVuIiwicGxheWVyRHJhZnQiOnsicGxheWVySWQiOiJwbGF5ZXIuY2FyZWVyLnByb3RhZ29uaXN0" +
            "IiwiZGlzcGxheU5hbWUiOiJDYXJlZXIgUHJvdGFnb25pc3QiLCJqZXJzZXlOdW1iZXIiOjJ9LCJvbmJvYXJkaW5nIjp7InN0YWdlcyI6W3sic3RhZ2VOdW1i" +
            "ZXIiOjEsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDEwMSIsInJhbmRvbVZlcnNpb24iOjEsImNob2ljZUlkIjoi" +
            "c3RhZ2UtMS1jaG9pY2UiLCJyZXNvbHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoic3RhZ2UtMS1yZXN1bHQiLCJwZXJ0dXJiYXRpb24iOjF9XX0seyJzdGFn" +
            "ZU51bWJlciI6Miwib2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTAyIiwicmFuZG9tVmVyc2lvbiI6MSwiY2hvaWNl" +
            "SWQiOiJzdGFnZS0yLWNob2ljZSIsInJlc29sdmVkT3V0cHV0cyI6W3sib3V0cHV0SWQiOiJzdGFnZS0yLXJlc3VsdCIsInBlcnR1cmJhdGlvbiI6Mn1dfSx7" +
            "InN0YWdlTnVtYmVyIjozLCJvY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDMiLCJyYW5kb21WZXJzaW9uIjoxLCJj" +
            "aG9pY2VJZCI6InN0YWdlLTMtY2hvaWNlIiwicmVzb2x2ZWRPdXRwdXRzIjpbeyJvdXRwdXRJZCI6InN0YWdlLTMtcmVzdWx0IiwicGVydHVyYmF0aW9uIjoz" +
            "fV19XSwibmV4dFN0YWdlTnVtYmVyIjowLCJpc0Zvcm1hbGx5RW5yb2xsZWQiOnRydWV9LCJwcm9ncmVzc2lvbiI6eyJraW5kIjoiYXdhaXRpbmdfbWF0Y2gi" +
            "LCJwaGFzZSI6InVuaXZlcnNpdHkiLCJ0cnlvdXRTdGFnZSI6MCwid2Vla1BsYW4iOnsicGxhbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAw" +
            "MDAwNjAwIiwic2Vhc29uIjoxLCJ3ZWVrIjoxLCJzbG90cyI6W3sic2xvdEFjdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjEw" +
            "Iiwib2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjExIiwia2luZCI6InNwZWNpYWxpemVkX3RyYWluaW5nIiwiY29u" +
            "dGVudElkIjoid2Vla19hY3Rpb24uc3BlY2lhbGl6ZWQuc3Bpa2UifSx7InNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAw" +
            "MDYyMCIsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYyMSIsImtpbmQiOiJzdHJlbmd0aF90cmFpbmluZyIsImNv" +
            "bnRlbnRJZCI6IndlZWtfYWN0aW9uLnN0cmVuZ3RoLmp1bXAifSx7InNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYz" +
            "MCIsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYzMSIsImtpbmQiOiJtYXRjaCIsImNvbnRlbnRJZCI6InNjaGVk" +
            "dWxlLnUxdzEubWF0Y2guMDEifV0sImlzQ29uZmlybWVkIjp0cnVlfSwibmV4dFNsb3ROdW1iZXIiOjAsInBlbmRpbmdFdmVudCI6bnVsbCwibWF0Y2hTZXNz" +
            "aW9uSWQiOiI1NTU1NTU1NS01NTU1LTU1NTUtNTU1NS01NTU1NTU1NTU1NTUifSwidHJhaW5pbmdFbXBoYXNlcyI6W3sic291cmNlU2xvdEFjdGlvbklkIjoi" +
            "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjEwIiwiZGlyZWN0aW9uIjoic3Bpa2UiLCJib251c0Jhc2lzUG9pbnRzIjoxMDAwfSx7InNvdXJj" +
            "ZVNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYyMCIsImRpcmVjdGlvbiI6Imp1bXAiLCJib251c0Jhc2lzUG9pbnRz" +
            "IjoxMDAwfV0sInBlbmRpbmdNYXRjaCI6eyJzZXNzaW9uSWQiOiI1NTU1NTU1NS01NTU1LTU1NTUtNTU1NS01NTU1NTU1NTU1NTUiLCJjcmVhdGlvbk9wZXJh" +
            "dGlvbklkIjoiOTk5OTk5OTktOTk5OS05OTk5LTk5OTktOTk5OTk5OTk5OTk5IiwiY3JlYXRlZExpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMz" +
            "LTMzMzMzMzMzMzMzMyIsImNyZWF0ZWRSZXZpc2lvbiI6OSwidmVyc2lvbnMiOnsiY29udHJhY3RWZXJzaW9uIjoyLCJjb250ZW50VmVyc2lvbiI6MSwicnVs" +
            "ZXNldFZlcnNpb24iOjEsImNhcmVlclJhbmRvbUFsZ29yaXRobVZlcnNpb24iOjEsIm1hdGNoU2ltdWxhdGlvblZlcnNpb24iOm51bGwsIm1hdGNoUmFuZG9t" +
            "QWxnb3JpdGhtVmVyc2lvbiI6bnVsbH0sImV4ZWN1dGlvbk1vZGUiOiJmaXh0dXJlIiwiZml4dHVyZUlkIjoiZml4dHVyZS5jYXJlZXIudTF3MS42djYiLCJm" +
            "aXh0dXJlVmVyc2lvbiI6MSwibWF0Y2hTZWVkIjoyNTY0OTcwMSwiY29tcGV0aXRpb25JZCI6ImNvbXBldGl0aW9uLnVuaXZlcnNpdHkudjEiLCJzY2hlZHVs" +
            "ZUl0ZW1JZCI6InNjaGVkdWxlLnUxdzEubWF0Y2guMDEiLCJzb3VyY2VXZWVrUGxhbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjAw" +
            "Iiwic291cmNlU2xvdEFjdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjMwIiwic291cmNlQWN0aW9uT2NjdXJyZW5jZUlkIjoi" +
            "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjMxIiwicHJlTWF0Y2hQcmlvcml0eSI6ImF0dGFja19maXJzdCIsImNvbnRleHRIYXNoIjoiZGE1" +
            "NzBjZmY5NzJkMjgwYWNiOTMwN2VkYjcxNWJjZWY4OGEwZjk1OGU3NWVhNjE1MDcyYTViZTI1ZWRmMDUyNyIsImNhbm9uaWNhbENvbnRleHRVdGY4QmFzZTY0" +
            "IjoiZXlKMlpYSnphVzl1Y3lJNmV5SmpiMjUwY21GamRGWmxjbk5wYjI0aU9qSXNJbU52Ym5SbGJuUldaWEp6YVc5dUlqb3hMQ0p5ZFd4bGMyVjBWbVZ5YzJs" +
            "dmJpSTZNU3dpWTJGeVpXVnlVbUZ1Wkc5dFFXeG5iM0pwZEdodFZtVnljMmx2YmlJNk1Td2liV0YwWTJoVGFXMTFiR0YwYVc5dVZtVnljMmx2YmlJNmJuVnNi" +
            "Q3dpYldGMFkyaFNZVzVrYjIxQmJHZHZjbWwwYUcxV1pYSnphVzl1SWpwdWRXeHNmU3dpYzJWemMybHZia2xrSWpvaU5UVTFOVFUxTlRVdE5UVTFOUzAxTlRV" +
            "MUxUVTFOVFV0TlRVMU5UVTFOVFUxTlRVMUlpd2laWGhsWTNWMGFXOXVUVzlrWlNJNkltWnBlSFIxY21VaUxDSm1hWGgwZFhKbFNXUWlPaUptYVhoMGRYSmxM" +
            "bU5oY21WbGNpNTFNWGN4TGpaMk5pSXNJbVpwZUhSMWNtVldaWEp6YVc5dUlqb3hMQ0p0WVhSamFGTmxaV1FpT2pJMU5qUTVOekF4TENKamIyMXdaWFJwZEds" +
            "dmJrbGtJam9pWTI5dGNHVjBhWFJwYjI0dWRXNXBkbVZ5YzJsMGVTNTJNU0lzSW5OamFHVmtkV3hsU1hSbGJVbGtJam9pYzJOb1pXUjFiR1V1ZFRGM01TNXRZ" +
            "WFJqYUM0d01TSXNJbWx0Y0c5eWRHRnVZMlZDWVhOcGMxQnZhVzUwY3lJNk56VXdNQ3dpWm05eWJXRjBJanA3SW10cGJtUWlPaUpwYm1SdmIzSmZOblkySWl3" +
            "aWRHVmhiVk5wZW1VaU9qWXNJbk5sZEhOVWIxZHBiaUk2TVN3aWMyVjBWR0Z5WjJWMFVHOXBiblJ6SWpveU5Td2liV2x1YVcxMWJVeGxZV1JRYjJsdWRITWlP" +
            "ako5TENKd2NtVk5ZWFJqYUZCeWFXOXlhWFI1SWpvaVlYUjBZV05yWDJacGNuTjBJaXdpZEdWaGJYTWlPbHQ3SW5SbFlXMUpaQ0k2SW5SbFlXMHVkVzVwZG1W" +
            "eWMybDBlUzVtYVhKemRDSXNJbk5wWkdVaU9pSm9iMjFsSWl3aWNHeGhlV1Z5Y3lJNlczc2ljR3hoZVdWeVNXUWlPaUp3YkdGNVpYSXVhRzl0WlM1dmNIQnZj" +
            "MmwwWlNJc0ltcGxjbk5sZVU1MWJXSmxjaUk2TVN3aWNHOXphWFJwYjI0aU9pSnZjSEJ2YzJsMFpTSXNJbkp2ZEdGMGFXOXVVMnh2ZENJNk1Td2labWwwYm1W" +
            "emMwSmhjMmx6VUc5cGJuUnpJam81TURBd0xDSmhZbWxzYVhScFpYTWlPbnNpYzNCcGEyVkNZWE5wYzFCdmFXNTBjeUk2TmpFd01Dd2ljMlZ5ZG1WQ1lYTnBj" +
            "MUJ2YVc1MGN5STZOakV3TVN3aWNtVmpaWEIwYVc5dVFtRnphWE5RYjJsdWRITWlPall4TURJc0ltUmxabVZ1YzJWQ1lYTnBjMUJ2YVc1MGN5STZOakV3TXl3" +
            "aVlteHZZMnRDWVhOcGMxQnZhVzUwY3lJNk5qRXdOQ3dpYlc5MlpXMWxiblJDWVhOcGMxQnZhVzUwY3lJNk5qRXdOU3dpYW5WdGNFSmhjMmx6VUc5cGJuUnpJ" +
            "am8yTVRBMkxDSnpkR0Z0YVc1aFFtRnphWE5RYjJsdWRITWlPall4TURkOWZTeDdJbkJzWVhsbGNrbGtJam9pY0d4aGVXVnlMbU5oY21WbGNpNXdjbTkwWVdk" +
            "dmJtbHpkQ0lzSW1wbGNuTmxlVTUxYldKbGNpSTZNaXdpY0c5emFYUnBiMjRpT2lKdmRYUnphV1JsWDJocGRIUmxjaUlzSW5KdmRHRjBhVzl1VTJ4dmRDSTZN" +
            "aXdpWm1sMGJtVnpjMEpoYzJselVHOXBiblJ6SWpvNE9EQXdMQ0poWW1sc2FYUnBaWE1pT25zaWMzQnBhMlZDWVhOcGMxQnZhVzUwY3lJNk56RXlNeXdpYzJW" +
            "eWRtVkNZWE5wYzFCdmFXNTBjeUk2TmpJek5Dd2ljbVZqWlhCMGFXOXVRbUZ6YVhOUWIybHVkSE1pT2pjek5EVXNJbVJsWm1WdWMyVkNZWE5wYzFCdmFXNTBj" +
            "eUk2TmpRMU5pd2lZbXh2WTJ0Q1lYTnBjMUJ2YVc1MGN5STZOelUyTnl3aWJXOTJaVzFsYm5SQ1lYTnBjMUJ2YVc1MGN5STZOalkzT0N3aWFuVnRjRUpoYzJs" +
            "elVHOXBiblJ6SWpvM056ZzVMQ0p6ZEdGdGFXNWhRbUZ6YVhOUWIybHVkSE1pT2pZNE9UQjlmU3g3SW5Cc1lYbGxja2xrSWpvaWNHeGhlV1Z5TG1odmJXVXVi" +
            "V2xrWkd4bElpd2lhbVZ5YzJWNVRuVnRZbVZ5SWpvekxDSndiM05wZEdsdmJpSTZJbTFwWkdSc1pWOWliRzlqYTJWeUlpd2ljbTkwWVhScGIyNVRiRzkwSWpv" +
            "ekxDSm1hWFJ1WlhOelFtRnphWE5RYjJsdWRITWlPamt3TURBc0ltRmlhV3hwZEdsbGN5STZleUp6Y0dsclpVSmhjMmx6VUc5cGJuUnpJam8yTXpBd0xDSnpa" +
            "WEoyWlVKaGMybHpVRzlwYm5SeklqbzJNekF4TENKeVpXTmxjSFJwYjI1Q1lYTnBjMUJ2YVc1MGN5STZOak13TWl3aVpHVm1aVzV6WlVKaGMybHpVRzlwYm5S" +
            "eklqbzJNekF6TENKaWJHOWphMEpoYzJselVHOXBiblJ6SWpvMk16QTBMQ0p0YjNabGJXVnVkRUpoYzJselVHOXBiblJ6SWpvMk16QTFMQ0pxZFcxd1FtRnph" +
            "WE5RYjJsdWRITWlPall6TURZc0luTjBZVzFwYm1GQ1lYTnBjMUJ2YVc1MGN5STZOak13TjMxOUxIc2ljR3hoZVdWeVNXUWlPaUp3YkdGNVpYSXVhRzl0WlM1" +
            "elpYUjBaWElpTENKcVpYSnpaWGxPZFcxaVpYSWlPalFzSW5CdmMybDBhVzl1SWpvaWMyVjBkR1Z5SWl3aWNtOTBZWFJwYjI1VGJHOTBJam8wTENKbWFYUnVa" +
            "WE56UW1GemFYTlFiMmx1ZEhNaU9qa3dNREFzSW1GaWFXeHBkR2xsY3lJNmV5SnpjR2xyWlVKaGMybHpVRzlwYm5SeklqbzJOREF3TENKelpYSjJaVUpoYzJs" +
            "elVHOXBiblJ6SWpvMk5EQXhMQ0p5WldObGNIUnBiMjVDWVhOcGMxQnZhVzUwY3lJNk5qUXdNaXdpWkdWbVpXNXpaVUpoYzJselVHOXBiblJ6SWpvMk5EQXpM" +
            "Q0ppYkc5amEwSmhjMmx6VUc5cGJuUnpJam8yTkRBMExDSnRiM1psYldWdWRFSmhjMmx6VUc5cGJuUnpJam8yTkRBMUxDSnFkVzF3UW1GemFYTlFiMmx1ZEhN" +
            "aU9qWTBNRFlzSW5OMFlXMXBibUZDWVhOcGMxQnZhVzUwY3lJNk5qUXdOMzE5TEhzaWNHeGhlV1Z5U1dRaU9pSndiR0Y1WlhJdWFHOXRaUzV2ZFhSemFXUmxM" +
            "bUlpTENKcVpYSnpaWGxPZFcxaVpYSWlPalVzSW5CdmMybDBhVzl1SWpvaWIzVjBjMmxrWlY5b2FYUjBaWElpTENKeWIzUmhkR2x2YmxOc2IzUWlPalVzSW1a" +
            "cGRHNWxjM05DWVhOcGMxQnZhVzUwY3lJNk9UQXdNQ3dpWVdKcGJHbDBhV1Z6SWpwN0luTndhV3RsUW1GemFYTlFiMmx1ZEhNaU9qWTFNREFzSW5ObGNuWmxR" +
            "bUZ6YVhOUWIybHVkSE1pT2pZMU1ERXNJbkpsWTJWd2RHbHZia0poYzJselVHOXBiblJ6SWpvMk5UQXlMQ0prWldabGJuTmxRbUZ6YVhOUWIybHVkSE1pT2pZ" +
            "MU1ETXNJbUpzYjJOclFtRnphWE5RYjJsdWRITWlPalkxTURRc0ltMXZkbVZ0Wlc1MFFtRnphWE5RYjJsdWRITWlPalkxTURVc0ltcDFiWEJDWVhOcGMxQnZh" +
            "VzUwY3lJNk5qVXdOaXdpYzNSaGJXbHVZVUpoYzJselVHOXBiblJ6SWpvMk5UQTNmWDBzZXlKd2JHRjVaWEpKWkNJNkluQnNZWGxsY2k1b2IyMWxMbXhwWW1W" +
            "eWJ5SXNJbXBsY25ObGVVNTFiV0psY2lJNk5pd2ljRzl6YVhScGIyNGlPaUpzYVdKbGNtOGlMQ0p5YjNSaGRHbHZibE5zYjNRaU9qWXNJbVpwZEc1bGMzTkNZ" +
            "WE5wYzFCdmFXNTBjeUk2T1RBd01Dd2lZV0pwYkdsMGFXVnpJanA3SW5Od2FXdGxRbUZ6YVhOUWIybHVkSE1pT2pZMk1EQXNJbk5sY25abFFtRnphWE5RYjJs" +
            "dWRITWlPalkyTURFc0luSmxZMlZ3ZEdsdmJrSmhjMmx6VUc5cGJuUnpJam8yTmpBeUxDSmtaV1psYm5ObFFtRnphWE5RYjJsdWRITWlPalkyTURNc0ltSnNi" +
            "Mk5yUW1GemFYTlFiMmx1ZEhNaU9qWTJNRFFzSW0xdmRtVnRaVzUwUW1GemFYTlFiMmx1ZEhNaU9qWTJNRFVzSW1wMWJYQkNZWE5wYzFCdmFXNTBjeUk2TmpZ" +
            "d05pd2ljM1JoYldsdVlVSmhjMmx6VUc5cGJuUnpJam8yTmpBM2ZYMWRmU3g3SW5SbFlXMUpaQ0k2SW5SbFlXMHVkVzVwZG1WeWMybDBlUzV5YVhaaGJDSXNJ" +
            "bk5wWkdVaU9pSmhkMkY1SWl3aWNHeGhlV1Z5Y3lJNlczc2ljR3hoZVdWeVNXUWlPaUp3YkdGNVpYSXVZWGRoZVM1dmNIQnZjMmwwWlNJc0ltcGxjbk5sZVU1" +
            "MWJXSmxjaUk2TVN3aWNHOXphWFJwYjI0aU9pSnZjSEJ2YzJsMFpTSXNJbkp2ZEdGMGFXOXVVMnh2ZENJNk1Td2labWwwYm1WemMwSmhjMmx6VUc5cGJuUnpJ" +
            "am81TURBd0xDSmhZbWxzYVhScFpYTWlPbnNpYzNCcGEyVkNZWE5wYzFCdmFXNTBjeUk2TmpFd01Dd2ljMlZ5ZG1WQ1lYTnBjMUJ2YVc1MGN5STZOakV3TVN3" +
            "aWNtVmpaWEIwYVc5dVFtRnphWE5RYjJsdWRITWlPall4TURJc0ltUmxabVZ1YzJWQ1lYTnBjMUJ2YVc1MGN5STZOakV3TXl3aVlteHZZMnRDWVhOcGMxQnZh" +
            "VzUwY3lJNk5qRXdOQ3dpYlc5MlpXMWxiblJDWVhOcGMxQnZhVzUwY3lJNk5qRXdOU3dpYW5WdGNFSmhjMmx6VUc5cGJuUnpJam8yTVRBMkxDSnpkR0Z0YVc1" +
            "aFFtRnphWE5RYjJsdWRITWlPall4TURkOWZTeDdJbkJzWVhsbGNrbGtJam9pY0d4aGVXVnlMbUYzWVhrdWIzVjBjMmxrWlM1aElpd2lhbVZ5YzJWNVRuVnRZ" +
            "bVZ5SWpveUxDSndiM05wZEdsdmJpSTZJbTkxZEhOcFpHVmZhR2wwZEdWeUlpd2ljbTkwWVhScGIyNVRiRzkwSWpveUxDSm1hWFJ1WlhOelFtRnphWE5RYjJs" +
            "dWRITWlPamt3TURBc0ltRmlhV3hwZEdsbGN5STZleUp6Y0dsclpVSmhjMmx6VUc5cGJuUnpJam8yTWpBd0xDSnpaWEoyWlVKaGMybHpVRzlwYm5SeklqbzJN" +
            "akF4TENKeVpXTmxjSFJwYjI1Q1lYTnBjMUJ2YVc1MGN5STZOakl3TWl3aVpHVm1aVzV6WlVKaGMybHpVRzlwYm5SeklqbzJNakF6TENKaWJHOWphMEpoYzJs" +
            "elVHOXBiblJ6SWpvMk1qQTBMQ0p0YjNabGJXVnVkRUpoYzJselVHOXBiblJ6SWpvMk1qQTFMQ0pxZFcxd1FtRnphWE5RYjJsdWRITWlPall5TURZc0luTjBZ" +
            "VzFwYm1GQ1lYTnBjMUJ2YVc1MGN5STZOakl3TjMxOUxIc2ljR3hoZVdWeVNXUWlPaUp3YkdGNVpYSXVZWGRoZVM1dGFXUmtiR1VpTENKcVpYSnpaWGxPZFcx" +
            "aVpYSWlPak1zSW5CdmMybDBhVzl1SWpvaWJXbGtaR3hsWDJKc2IyTnJaWElpTENKeWIzUmhkR2x2YmxOc2IzUWlPak1zSW1acGRHNWxjM05DWVhOcGMxQnZh" +
            "VzUwY3lJNk9UQXdNQ3dpWVdKcGJHbDBhV1Z6SWpwN0luTndhV3RsUW1GemFYTlFiMmx1ZEhNaU9qWXpNREFzSW5ObGNuWmxRbUZ6YVhOUWIybHVkSE1pT2pZ" +
            "ek1ERXNJbkpsWTJWd2RHbHZia0poYzJselVHOXBiblJ6SWpvMk16QXlMQ0prWldabGJuTmxRbUZ6YVhOUWIybHVkSE1pT2pZek1ETXNJbUpzYjJOclFtRnph" +
            "WE5RYjJsdWRITWlPall6TURRc0ltMXZkbVZ0Wlc1MFFtRnphWE5RYjJsdWRITWlPall6TURVc0ltcDFiWEJDWVhOcGMxQnZhVzUwY3lJNk5qTXdOaXdpYzNS" +
            "aGJXbHVZVUpoYzJselVHOXBiblJ6SWpvMk16QTNmWDBzZXlKd2JHRjVaWEpKWkNJNkluQnNZWGxsY2k1aGQyRjVMbk5sZEhSbGNpSXNJbXBsY25ObGVVNTFi" +
            "V0psY2lJNk5Dd2ljRzl6YVhScGIyNGlPaUp6WlhSMFpYSWlMQ0p5YjNSaGRHbHZibE5zYjNRaU9qUXNJbVpwZEc1bGMzTkNZWE5wYzFCdmFXNTBjeUk2T1RB" +
            "d01Dd2lZV0pwYkdsMGFXVnpJanA3SW5Od2FXdGxRbUZ6YVhOUWIybHVkSE1pT2pZME1EQXNJbk5sY25abFFtRnphWE5RYjJsdWRITWlPalkwTURFc0luSmxZ" +
            "MlZ3ZEdsdmJrSmhjMmx6VUc5cGJuUnpJam8yTkRBeUxDSmtaV1psYm5ObFFtRnphWE5RYjJsdWRITWlPalkwTURNc0ltSnNiMk5yUW1GemFYTlFiMmx1ZEhN" +
            "aU9qWTBNRFFzSW0xdmRtVnRaVzUwUW1GemFYTlFiMmx1ZEhNaU9qWTBNRFVzSW1wMWJYQkNZWE5wYzFCdmFXNTBjeUk2TmpRd05pd2ljM1JoYldsdVlVSmhj" +
            "Mmx6VUc5cGJuUnpJam8yTkRBM2ZYMHNleUp3YkdGNVpYSkpaQ0k2SW5Cc1lYbGxjaTVoZDJGNUxtOTFkSE5wWkdVdVlpSXNJbXBsY25ObGVVNTFiV0psY2lJ" +
            "Nk5Td2ljRzl6YVhScGIyNGlPaUp2ZFhSemFXUmxYMmhwZEhSbGNpSXNJbkp2ZEdGMGFXOXVVMnh2ZENJNk5Td2labWwwYm1WemMwSmhjMmx6VUc5cGJuUnpJ" +
            "am81TURBd0xDSmhZbWxzYVhScFpYTWlPbnNpYzNCcGEyVkNZWE5wYzFCdmFXNTBjeUk2TmpVd01Dd2ljMlZ5ZG1WQ1lYTnBjMUJ2YVc1MGN5STZOalV3TVN3" +
            "aWNtVmpaWEIwYVc5dVFtRnphWE5RYjJsdWRITWlPalkxTURJc0ltUmxabVZ1YzJWQ1lYTnBjMUJ2YVc1MGN5STZOalV3TXl3aVlteHZZMnRDWVhOcGMxQnZh" +
            "VzUwY3lJNk5qVXdOQ3dpYlc5MlpXMWxiblJDWVhOcGMxQnZhVzUwY3lJNk5qVXdOU3dpYW5WdGNFSmhjMmx6VUc5cGJuUnpJam8yTlRBMkxDSnpkR0Z0YVc1" +
            "aFFtRnphWE5RYjJsdWRITWlPalkxTURkOWZTeDdJbkJzWVhsbGNrbGtJam9pY0d4aGVXVnlMbUYzWVhrdWJHbGlaWEp2SWl3aWFtVnljMlY1VG5WdFltVnlJ" +
            "am8yTENKd2IzTnBkR2x2YmlJNklteHBZbVZ5YnlJc0luSnZkR0YwYVc5dVUyeHZkQ0k2Tml3aVptbDBibVZ6YzBKaGMybHpVRzlwYm5SeklqbzVNREF3TENK" +
            "aFltbHNhWFJwWlhNaU9uc2ljM0JwYTJWQ1lYTnBjMUJ2YVc1MGN5STZOall3TUN3aWMyVnlkbVZDWVhOcGMxQnZhVzUwY3lJNk5qWXdNU3dpY21WalpYQjBh" +
            "Vzl1UW1GemFYTlFiMmx1ZEhNaU9qWTJNRElzSW1SbFptVnVjMlZDWVhOcGMxQnZhVzUwY3lJNk5qWXdNeXdpWW14dlkydENZWE5wYzFCdmFXNTBjeUk2TmpZ" +
            "d05Dd2liVzkyWlcxbGJuUkNZWE5wYzFCdmFXNTBjeUk2TmpZd05Td2lhblZ0Y0VKaGMybHpVRzlwYm5SeklqbzJOakEyTENKemRHRnRhVzVoUW1GemFYTlFi" +
            "Mmx1ZEhNaU9qWTJNRGQ5ZlYxOVhTd2lZMjl1ZEdWNGRFaGhjMmdpT2lKa1lUVTNNR05tWmprM01tUXlPREJoWTJJNU16QTNaV1JpTnpFMVltTmxaamc0WVRC" +
            "bU9UVTRaVGMxWldFMk1UVXdOekpoTldKbE1qVmxaR1l3TlRJM0luMD0iLCJob21lVGVhbUlkIjoidGVhbS51bml2ZXJzaXR5LmZpcnN0IiwiYXdheVRlYW1J" +
            "ZCI6InRlYW0udW5pdmVyc2l0eS5yaXZhbCIsIm9yZGVyZWRQbGF5ZXJJZHMiOlsicGxheWVyLmhvbWUub3Bwb3NpdGUiLCJwbGF5ZXIuY2FyZWVyLnByb3Rh" +
            "Z29uaXN0IiwicGxheWVyLmhvbWUubWlkZGxlIiwicGxheWVyLmhvbWUuc2V0dGVyIiwicGxheWVyLmhvbWUub3V0c2lkZS5iIiwicGxheWVyLmhvbWUubGli" +
            "ZXJvIiwicGxheWVyLmF3YXkub3Bwb3NpdGUiLCJwbGF5ZXIuYXdheS5vdXRzaWRlLmEiLCJwbGF5ZXIuYXdheS5taWRkbGUiLCJwbGF5ZXIuYXdheS5zZXR0" +
            "ZXIiLCJwbGF5ZXIuYXdheS5vdXRzaWRlLmIiLCJwbGF5ZXIuYXdheS5saWJlcm8iXSwicHJvdGFnb25pc3RQbGF5ZXJJZCI6InBsYXllci5jYXJlZXIucHJv" +
            "dGFnb25pc3QiLCJmcm96ZW5UcmFpbmluZ0VtcGhhc2VzIjpbeyJkaXJlY3Rpb24iOiJzcGlrZSIsInNvdXJjZVNsb3RBY3Rpb25JZHMiOlsiMDAwMDAwMDAt" +
            "MDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjEwIl0sInRvdGFsQm9udXNCYXNpc1BvaW50cyI6MTAwMH0seyJkaXJlY3Rpb24iOiJqdW1wIiwic291cmNlU2xv" +
            "dEFjdGlvbklkcyI6WyIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDA2MjAiXSwidG90YWxCb251c0Jhc2lzUG9pbnRzIjoxMDAwfV19LCJwbGF5" +
            "ZXIiOnsicGxheWVySWQiOiJwbGF5ZXIuY2FyZWVyLnByb3RhZ29uaXN0IiwiZGlzcGxheU5hbWUiOiJDYXJlZXIgUHJvdGFnb25pc3QiLCJqZXJzZXlOdW1i" +
            "ZXIiOjIsImF0dHJpYnV0ZXMiOnsic3Bpa2UiOnsiYWJpbGl0eUJhc2lzUG9pbnRzIjo3MTIzLCJncm93dGhFeHBlcmllbmNlIjoxMDF9LCJzZXJ2ZSI6eyJh" +
            "YmlsaXR5QmFzaXNQb2ludHMiOjYyMzQsImdyb3d0aEV4cGVyaWVuY2UiOjIwMn0sInJlY2VwdGlvbiI6eyJhYmlsaXR5QmFzaXNQb2ludHMiOjczNDUsImdy" +
            "b3d0aEV4cGVyaWVuY2UiOjMwM30sImRlZmVuc2UiOnsiYWJpbGl0eUJhc2lzUG9pbnRzIjo2NDU2LCJncm93dGhFeHBlcmllbmNlIjo0MDR9LCJibG9jayI6" +
            "eyJhYmlsaXR5QmFzaXNQb2ludHMiOjc1NjcsImdyb3d0aEV4cGVyaWVuY2UiOjUwNX0sIm1vdmVtZW50Ijp7ImFiaWxpdHlCYXNpc1BvaW50cyI6NjY3OCwi" +
            "Z3Jvd3RoRXhwZXJpZW5jZSI6NjA2fSwianVtcCI6eyJhYmlsaXR5QmFzaXNQb2ludHMiOjc3ODksImdyb3d0aEV4cGVyaWVuY2UiOjcwN30sInN0YW1pbmEi" +
            "OnsiYWJpbGl0eUJhc2lzUG9pbnRzIjo2ODkwLCJncm93dGhFeHBlcmllbmNlIjo4MDh9fX0sInRlYW1JZCI6InRlYW0udW5pdmVyc2l0eS5maXJzdCIsInBv" +
            "dGVudGlhbEdyYWRlIjoiYiIsImZhdGlndWUiOjEyLCJtaW5kc2V0Ijo1NiwiY29hY2hUcnVzdCI6NjMsIm1hdGNoSGlzdG9yeSI6W10sIm9wZXJhdGlvblJl" +
            "Y2VpcHRzIjpbeyJvcGVyYXRpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDgwMSIsIm9wZXJhdGlvbktpbmQiOiJjcmVhdGVfY2Fy" +
            "ZWVyIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjowLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOm51bGwsImNob2ljZUlkIjpudWxsLCJ3ZWVrUGxhbklkIjpudWxs" +
            "LCJzbG90QWN0aW9uSWQiOm51bGwsImFjdGlvbk9jY3VycmVuY2VJZCI6bnVsbCwiZXZlbnRPY2N1cnJlbmNlSWQiOm51bGwsIm9wdGlvbklkIjpudWxsLCJt" +
            "YXRjaFNlc3Npb25JZCI6bnVsbCwic2NoZWR1bGVJdGVtSWQiOm51bGwsImNvbnRleHRIYXNoIjpudWxsfSwiaW5wdXRGaW5nZXJwcmludCI6ImJiYmJiYmJi" +
            "YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmIiLCJhcHBsaWVkTGluZWFnZUlkIjoiMzMzMzMzMzMtMzMz" +
            "My0zMzMzLTMzMzMtMzMzMzMzMzMzMzMzIiwiYXBwbGllZFJldmlzaW9uIjoxLCJjb21wbGV0ZWRBdFV0Y01zIjoxLCJvdXRjb21lS2luZCI6ImNhcmVlcl9j" +
            "cmVhdGVkIiwib3V0Y29tZVN1bW1hcnkiOnsidHJ5b3V0UmVzb2x2ZWRPdXRwdXRzIjpbXSwiZ3Jvd3RoRXhwZXJpZW5jZURlbHRhIjpudWxsLCJmYXRpZ3Vl" +
            "RGVsdGEiOm51bGwsIm1pbmRzZXREZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsLCJtYXRjaFNlc3Npb25JZCI6bnVsbCwiY29udGV4dEhhc2gi" +
            "Om51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwODAyIiwib3BlcmF0aW9uS2luZCI6ImNvbmZpcm1fdHJ5" +
            "b3V0X3N0YWdlIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjoxLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAw" +
            "MDAxMDEiLCJjaG9pY2VJZCI6InN0YWdlLTEtY2hvaWNlIiwid2Vla1BsYW5JZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNl" +
            "SWQiOm51bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsInNjaGVkdWxlSXRlbUlkIjpu" +
            "dWxsLCJjb250ZXh0SGFzaCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2Nj" +
            "Y2NjY2NjY2NjY2NjY2NjY2NjIiwiYXBwbGllZExpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMzLTMzMzMzMzMzMzMzMyIsImFwcGxpZWRSZXZp" +
            "c2lvbiI6MiwiY29tcGxldGVkQXRVdGNNcyI6Miwib3V0Y29tZUtpbmQiOiJ0cnlvdXRfYWR2YW5jZWQiLCJvdXRjb21lU3VtbWFyeSI6eyJ0cnlvdXRSZXNv" +
            "bHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoic3RhZ2UtMS1yZXN1bHQiLCJwZXJ0dXJiYXRpb24iOjF9XSwiZ3Jvd3RoRXhwZXJpZW5jZURlbHRhIjpudWxs" +
            "LCJmYXRpZ3VlRGVsdGEiOm51bGwsIm1pbmRzZXREZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsLCJtYXRjaFNlc3Npb25JZCI6bnVsbCwiY29u" +
            "dGV4dEhhc2giOm51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwODAzIiwib3BlcmF0aW9uS2luZCI6ImNv" +
            "bmZpcm1fdHJ5b3V0X3N0YWdlIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjoyLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAw" +
            "MC0wMDAwMDAwMDAxMDIiLCJjaG9pY2VJZCI6InN0YWdlLTItY2hvaWNlIiwid2Vla1BsYW5JZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25P" +
            "Y2N1cnJlbmNlSWQiOm51bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsInNjaGVkdWxl" +
            "SXRlbUlkIjpudWxsLCJjb250ZXh0SGFzaCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRk" +
            "ZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkIiwiYXBwbGllZExpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMzLTMzMzMzMzMzMzMzMyIsImFw" +
            "cGxpZWRSZXZpc2lvbiI6MywiY29tcGxldGVkQXRVdGNNcyI6Mywib3V0Y29tZUtpbmQiOiJ0cnlvdXRfYWR2YW5jZWQiLCJvdXRjb21lU3VtbWFyeSI6eyJ0" +
            "cnlvdXRSZXNvbHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoic3RhZ2UtMi1yZXN1bHQiLCJwZXJ0dXJiYXRpb24iOjJ9XSwiZ3Jvd3RoRXhwZXJpZW5jZURl" +
            "bHRhIjpudWxsLCJmYXRpZ3VlRGVsdGEiOm51bGwsIm1pbmRzZXREZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsLCJtYXRjaFNlc3Npb25JZCI6" +
            "bnVsbCwiY29udGV4dEhhc2giOm51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwODA0Iiwib3BlcmF0aW9u" +
            "S2luZCI6ImNvbmZpcm1fdHJ5b3V0X3N0YWdlIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjozLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAw" +
            "LTAwMDAtMDAwMC0wMDAwMDAwMDAxMDMiLCJjaG9pY2VJZCI6InN0YWdlLTMtY2hvaWNlIiwid2Vla1BsYW5JZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxs" +
            "LCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hTZXNzaW9uSWQiOm51bGws" +
            "InNjaGVkdWxlSXRlbUlkIjpudWxsLCJjb250ZXh0SGFzaCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVl" +
            "ZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlIiwiYXBwbGllZExpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMzLTMzMzMzMzMz" +
            "MzMzMyIsImFwcGxpZWRSZXZpc2lvbiI6NCwiY29tcGxldGVkQXRVdGNNcyI6NCwib3V0Y29tZUtpbmQiOiJ0cnlvdXRfYWR2YW5jZWQiLCJvdXRjb21lU3Vt" +
            "bWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoic3RhZ2UtMy1yZXN1bHQiLCJwZXJ0dXJiYXRpb24iOjN9XSwiZ3Jvd3RoRXhw" +
            "ZXJpZW5jZURlbHRhIjpudWxsLCJmYXRpZ3VlRGVsdGEiOm51bGwsIm1pbmRzZXREZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsLCJtYXRjaFNl" +
            "c3Npb25JZCI6bnVsbCwiY29udGV4dEhhc2giOm51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwODA1Iiwi" +
            "b3BlcmF0aW9uS2luZCI6ImNvbmZpcm1fd2Vla19wbGFuIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjowLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOm51bGwsImNo" +
            "b2ljZUlkIjpudWxsLCJ3ZWVrUGxhbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwNjAwIiwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rp" +
            "b25PY2N1cnJlbmNlSWQiOm51bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsInNjaGVk" +
            "dWxlSXRlbUlkIjpudWxsLCJjb250ZXh0SGFzaCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" +
            "ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmIiwiYXBwbGllZExpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMzLTMzMzMzMzMzMzMzMyIs" +
            "ImFwcGxpZWRSZXZpc2lvbiI6NSwiY29tcGxldGVkQXRVdGNNcyI6NSwib3V0Y29tZUtpbmQiOiJ3ZWVrX3BsYW5fY29uZmlybWVkIiwib3V0Y29tZVN1bW1h" +
            "cnkiOnsidHJ5b3V0UmVzb2x2ZWRPdXRwdXRzIjpbXSwiZ3Jvd3RoRXhwZXJpZW5jZURlbHRhIjpudWxsLCJmYXRpZ3VlRGVsdGEiOm51bGwsIm1pbmRzZXRE" +
            "ZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsLCJtYXRjaFNlc3Npb25JZCI6bnVsbCwiY29udGV4dEhhc2giOm51bGx9fSx7Im9wZXJhdGlvbklk" +
            "IjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwODA2Iiwib3BlcmF0aW9uS2luZCI6ImV4ZWN1dGVfd2Vla19hY3Rpb24iLCJ0YXJnZXQiOnsi" +
            "dHJ5b3V0U3RhZ2UiOjAsInRyeW91dE9jY3VycmVuY2VJZCI6bnVsbCwiY2hvaWNlSWQiOm51bGwsIndlZWtQbGFuSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAt" +
            "MDAwMC0wMDAwMDAwMDA2MDAiLCJzbG90QWN0aW9uSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDA2MTAiLCJhY3Rpb25PY2N1cnJlbmNl" +
            "SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDA2MTEiLCJldmVudE9jY3VycmVuY2VJZCI6bnVsbCwib3B0aW9uSWQiOm51bGwsIm1hdGNo" +
            "U2Vzc2lvbklkIjpudWxsLCJzY2hlZHVsZUl0ZW1JZCI6bnVsbCwiY29udGV4dEhhc2giOm51bGx9LCJpbnB1dEZpbmdlcnByaW50IjoiYWFhYWFhYWFhYWFh" +
            "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYSIsImFwcGxpZWRMaW5lYWdlSWQiOiIzMzMzMzMzMy0zMzMzLTMz" +
            "MzMtMzMzMy0zMzMzMzMzMzMzMzMiLCJhcHBsaWVkUmV2aXNpb24iOjYsImNvbXBsZXRlZEF0VXRjTXMiOjYsIm91dGNvbWVLaW5kIjoic2xvdF9jb21wbGV0" +
            "ZWQiLCJvdXRjb21lU3VtbWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOltdLCJncm93dGhFeHBlcmllbmNlRGVsdGEiOnsic3Bpa2UiOjEyMCwic2Vy" +
            "dmUiOjAsInJlY2VwdGlvbiI6MCwiZGVmZW5zZSI6MCwiYmxvY2siOjAsIm1vdmVtZW50IjowLCJqdW1wIjowLCJzdGFtaW5hIjowfSwiZmF0aWd1ZURlbHRh" +
            "Ijo4LCJtaW5kc2V0RGVsdGEiOjAsImNvYWNoVHJ1c3REZWx0YSI6MCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsImNvbnRleHRIYXNoIjpudWxsfX0seyJvcGVy" +
            "YXRpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDgwNyIsIm9wZXJhdGlvbktpbmQiOiJyZXNvbHZlX2V2ZW50X2Nob2ljZSIsInRh" +
            "cmdldCI6eyJ0cnlvdXRTdGFnZSI6MCwidHJ5b3V0T2NjdXJyZW5jZUlkIjpudWxsLCJjaG9pY2VJZCI6bnVsbCwid2Vla1BsYW5JZCI6IjAwMDAwMDAwLTAw" +
            "MDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYwMCIsInNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYxMCIsImFjdGlvbk9j" +
            "Y3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYxMSIsImV2ZW50T2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAw" +
            "LTAwMDAtMDAwMDAwMDAwNjQwIiwib3B0aW9uSWQiOiJldmVudC50ZWFtX21lYWwub3B0aW9uLmF0dGVuZCIsIm1hdGNoU2Vzc2lvbklkIjpudWxsLCJzY2hl" +
            "ZHVsZUl0ZW1JZCI6bnVsbCwiY29udGV4dEhhc2giOm51bGx9LCJpbnB1dEZpbmdlcnByaW50IjoiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJi" +
            "YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYiIsImFwcGxpZWRMaW5lYWdlSWQiOiIzMzMzMzMzMy0zMzMzLTMzMzMtMzMzMy0zMzMzMzMzMzMzMzMi" +
            "LCJhcHBsaWVkUmV2aXNpb24iOjcsImNvbXBsZXRlZEF0VXRjTXMiOjcsIm91dGNvbWVLaW5kIjoiZXZlbnRfY2hvaWNlX2FwcGxpZWQiLCJvdXRjb21lU3Vt" +
            "bWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOltdLCJncm93dGhFeHBlcmllbmNlRGVsdGEiOnsic3Bpa2UiOjAsInNlcnZlIjowLCJyZWNlcHRpb24i" +
            "OjAsImRlZmVuc2UiOjAsImJsb2NrIjowLCJtb3ZlbWVudCI6MCwianVtcCI6MCwic3RhbWluYSI6MH0sImZhdGlndWVEZWx0YSI6NCwibWluZHNldERlbHRh" +
            "Ijo2LCJjb2FjaFRydXN0RGVsdGEiOjMsIm1hdGNoU2Vzc2lvbklkIjpudWxsLCJjb250ZXh0SGFzaCI6bnVsbH19LHsib3BlcmF0aW9uSWQiOiIwMDAwMDAw" +
            "MC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDA4MDgiLCJvcGVyYXRpb25LaW5kIjoiZXhlY3V0ZV93ZWVrX2FjdGlvbiIsInRhcmdldCI6eyJ0cnlvdXRTdGFn" +
            "ZSI6MCwidHJ5b3V0T2NjdXJyZW5jZUlkIjpudWxsLCJjaG9pY2VJZCI6bnVsbCwid2Vla1BsYW5JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAw" +
            "MDAwMDYwMCIsInNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYyMCIsImFjdGlvbk9jY3VycmVuY2VJZCI6IjAwMDAw" +
            "MDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYyMSIsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hTZXNzaW9uSWQi" +
            "Om51bGwsInNjaGVkdWxlSXRlbUlkIjpudWxsLCJjb250ZXh0SGFzaCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJjY2NjY2NjY2NjY2NjY2NjY2NjY2Nj" +
            "Y2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjIiwiYXBwbGllZExpbmVhZ2VJZCI6IjMzMzMzMzMzLTMzMzMtMzMzMy0zMzMzLTMz" +
            "MzMzMzMzMzMzMyIsImFwcGxpZWRSZXZpc2lvbiI6OCwiY29tcGxldGVkQXRVdGNNcyI6OCwib3V0Y29tZUtpbmQiOiJzbG90X2NvbXBsZXRlZCIsIm91dGNv" +
            "bWVTdW1tYXJ5Ijp7InRyeW91dFJlc29sdmVkT3V0cHV0cyI6W10sImdyb3d0aEV4cGVyaWVuY2VEZWx0YSI6eyJzcGlrZSI6MCwic2VydmUiOjAsInJlY2Vw" +
            "dGlvbiI6MCwiZGVmZW5zZSI6MCwiYmxvY2siOjAsIm1vdmVtZW50IjowLCJqdW1wIjoxMDAsInN0YW1pbmEiOjB9LCJmYXRpZ3VlRGVsdGEiOjEyLCJtaW5k" +
            "c2V0RGVsdGEiOjAsImNvYWNoVHJ1c3REZWx0YSI6MCwibWF0Y2hTZXNzaW9uSWQiOm51bGwsImNvbnRleHRIYXNoIjpudWxsfX0seyJvcGVyYXRpb25JZCI6" +
            "Ijk5OTk5OTk5LTk5OTktOTk5OS05OTk5LTk5OTk5OTk5OTk5OSIsIm9wZXJhdGlvbktpbmQiOiJjcmVhdGVfcGVuZGluZ19tYXRjaCIsInRhcmdldCI6eyJ0" +
            "cnlvdXRTdGFnZSI6MCwidHJ5b3V0T2NjdXJyZW5jZUlkIjpudWxsLCJjaG9pY2VJZCI6bnVsbCwid2Vla1BsYW5JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0w" +
            "MDAwLTAwMDAwMDAwMDYwMCIsInNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYzMCIsImFjdGlvbk9jY3VycmVuY2VJ" +
            "ZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDYzMSIsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbCwibWF0Y2hT" +
            "ZXNzaW9uSWQiOiI1NTU1NTU1NS01NTU1LTU1NTUtNTU1NS01NTU1NTU1NTU1NTUiLCJzY2hlZHVsZUl0ZW1JZCI6InNjaGVkdWxlLnUxdzEubWF0Y2guMDEi" +
            "LCJjb250ZXh0SGFzaCI6ImRhNTcwY2ZmOTcyZDI4MGFjYjkzMDdlZGI3MTViY2VmODhhMGY5NThlNzVlYTYxNTA3MmE1YmUyNWVkZjA1MjcifSwiaW5wdXRG" +
            "aW5nZXJwcmludCI6ImZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmYiLCJhcHBsaWVkTGlu" +
            "ZWFnZUlkIjoiMzMzMzMzMzMtMzMzMy0zMzMzLTMzMzMtMzMzMzMzMzMzMzMzIiwiYXBwbGllZFJldmlzaW9uIjo5LCJjb21wbGV0ZWRBdFV0Y01zIjoxMDAs" +
            "Im91dGNvbWVLaW5kIjoicGVuZGluZ19tYXRjaF9jcmVhdGVkIiwib3V0Y29tZVN1bW1hcnkiOnsidHJ5b3V0UmVzb2x2ZWRPdXRwdXRzIjpbXSwiZ3Jvd3Ro" +
            "RXhwZXJpZW5jZURlbHRhIjpudWxsLCJmYXRpZ3VlRGVsdGEiOm51bGwsIm1pbmRzZXREZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsLCJtYXRj" +
            "aFNlc3Npb25JZCI6IjU1NTU1NTU1LTU1NTUtNTU1NS01NTU1LTU1NTU1NTU1NTU1NSIsImNvbnRleHRIYXNoIjoiZGE1NzBjZmY5NzJkMjgwYWNiOTMwN2Vk" +
            "YjcxNWJjZWY4OGEwZjk1OGU3NWVhNjE1MDcyYTViZTI1ZWRmMDUyNyJ9fV0sInNldHRsZW1lbnRSZWNlaXB0cyI6W119";
        private const string ExecutedGoldenHash =
            "17afb674e1779f2d9eaa6ad52bce58906e86af7bf87147018e532408241e9e05";
        private const string UnsupportedExecutedV1GoldenBase64 =
            "eyJ2ZXJzaW9ucyI6eyJzY2hlbWFWZXJzaW9uIjoxLCJjb250ZW50VmVyc2lvbiI6MSwicnVsZXNldFZlcnNpb24iOjEsImNhcmVlclJhbmRvbUFsZ29yaXRo" +
            "bVZlcnNpb24iOjF9LCJpZGVudGl0eSI6eyJwcm9maWxlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJzYXZlSWQiOiIwMDAw" +
            "MDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDIiLCJsaW5lYWdlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDMiLCJyZXZp" +
            "c2lvbiI6NywicmVzdG9yZWRGcm9tVmVyc2lvblRva2VuIjp7ImxpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwNCIsInJl" +
            "dmlzaW9uIjoxLCJzbmFwc2hvdEhhc2giOiJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJi" +
            "In0sImNyZWF0ZWRBdFV0Y01zIjoxMDAwLCJ1cGRhdGVkQXRVdGNNcyI6MjAwMH0sImludGVncml0eSI6eyJzbmFwc2hvdEhhc2giOiI4YjI4M2VlNzI1YjI3" +
            "N2RmZDUzMzA2OGJmMDk4ZTMxZTE2ZjU0Zjc0MDk0NDk5YjY2ZDk4NGI1NDQ1YTY4ZGJkIn0sImNhcmVlclNlZWQiOiIwMDAxMDIwMzA0MDUwNjA3MDgwOTBh" +
            "MGIwYzBkMGUwZjEwMTExMjEzMTQxNTE2MTcxODE5MWExYjFjMWQxZTFmIiwiY2FyZWVyTmFtZSI6IlJvYWQgdG8gViBMZWFndWUiLCJwbGF5ZXJEcmFmdCI6" +
            "eyJwbGF5ZXJJZCI6InBsYXllci5hbHBoYSIsImRpc3BsYXlOYW1lIjoiTGluIiwiamVyc2V5TnVtYmVyIjoxMn0sIm9uYm9hcmRpbmciOnsic3RhZ2VzIjpb" +
            "eyJzdGFnZU51bWJlciI6MSwib2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTAxIiwicmFuZG9tVmVyc2lvbiI6MSwi" +
            "Y2hvaWNlSWQiOiJzdGFnZS0xLWNob2ljZSIsInJlc29sdmVkT3V0cHV0cyI6W3sib3V0cHV0SWQiOiJzdGFnZS0xLXByaW1hcnkiLCJwZXJ0dXJiYXRpb24i" +
            "OjEwfSx7Im91dHB1dElkIjoic3RhZ2UtMS1zZWNvbmRhcnkiLCJwZXJ0dXJiYXRpb24iOi01fV19LHsic3RhZ2VOdW1iZXIiOjIsIm9jY3VycmVuY2VJZCI6" +
            "IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDEwMiIsInJhbmRvbVZlcnNpb24iOjEsImNob2ljZUlkIjoic3RhZ2UtMi1jaG9pY2UiLCJyZXNv" +
            "bHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoic3RhZ2UtMi1wcmltYXJ5IiwicGVydHVyYmF0aW9uIjoxMH0seyJvdXRwdXRJZCI6InN0YWdlLTItc2Vjb25k" +
            "YXJ5IiwicGVydHVyYmF0aW9uIjotNX1dfSx7InN0YWdlTnVtYmVyIjozLCJvY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAw" +
            "MDAxMDMiLCJyYW5kb21WZXJzaW9uIjoxLCJjaG9pY2VJZCI6InN0YWdlLTMtY2hvaWNlIiwicmVzb2x2ZWRPdXRwdXRzIjpbeyJvdXRwdXRJZCI6InN0YWdl" +
            "LTMtcHJpbWFyeSIsInBlcnR1cmJhdGlvbiI6MTB9LHsib3V0cHV0SWQiOiJzdGFnZS0zLXNlY29uZGFyeSIsInBlcnR1cmJhdGlvbiI6LTV9XX1dLCJuZXh0" +
            "U3RhZ2VOdW1iZXIiOjAsImlzRm9ybWFsbHlFbnJvbGxlZCI6dHJ1ZX0sInByb2dyZXNzaW9uIjp7ImtpbmQiOiJwbGFubmVkIiwicGhhc2UiOiJ1bml2ZXJz" +
            "aXR5IiwidHJ5b3V0U3RhZ2UiOjAsIndlZWtQbGFuIjp7InBsYW5JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAxMCIsInNlYXNvbiI6" +
            "MSwid2VlayI6Miwic2xvdHMiOlt7InNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAxMSIsIm9jY3VycmVuY2VJZCI6" +
            "IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDA0MSIsImtpbmQiOiJzcGVjaWFsaXplZF90cmFpbmluZyIsImNvbnRlbnRJZCI6IndlZWtfYWN0" +
            "aW9uLnNwZWNpYWxpemVkLnNwaWtlIn0seyJzbG90QWN0aW9uSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMTIiLCJvY2N1cnJlbmNl" +
            "SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwNDIiLCJraW5kIjoicmVzdCIsImNvbnRlbnRJZCI6IndlZWtfYWN0aW9uLnJlc3Quc3Rh" +
            "bmRhcmQifSx7InNsb3RBY3Rpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAxMyIsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAw" +
            "MDAtMDAwMC0wMDAwLTAwMDAwMDAwMDA0MyIsImtpbmQiOiJtYXRjaCIsImNvbnRlbnRJZCI6InNjaGVkdWxlLnUxdzEubWF0Y2guMDEifV0sImlzQ29uZmly" +
            "bWVkIjp0cnVlfSwibmV4dFNsb3ROdW1iZXIiOjIsInBlbmRpbmdFdmVudCI6bnVsbH0sInRyYWluaW5nRW1waGFzZXMiOlt7InNvdXJjZVNsb3RBY3Rpb25J" +
            "ZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAxMSIsImRpcmVjdGlvbiI6InNwaWtlIiwiYm9udXNCYXNpc1BvaW50cyI6MTAwMH1dLCJw" +
            "bGF5ZXIiOnsicGxheWVySWQiOiJwbGF5ZXIuYWxwaGEiLCJkaXNwbGF5TmFtZSI6IkxpbiIsImplcnNleU51bWJlciI6MTIsImF0dHJpYnV0ZXMiOnsic3Bp" +
            "a2UiOnsiYWJpbGl0eUJhc2lzUG9pbnRzIjo1MTAwLCJncm93dGhFeHBlcmllbmNlIjoxMDF9LCJzZXJ2ZSI6eyJhYmlsaXR5QmFzaXNQb2ludHMiOjUyMDAs" +
            "Imdyb3d0aEV4cGVyaWVuY2UiOjEwMn0sInJlY2VwdGlvbiI6eyJhYmlsaXR5QmFzaXNQb2ludHMiOjUzMDAsImdyb3d0aEV4cGVyaWVuY2UiOjEwM30sImRl" +
            "ZmVuc2UiOnsiYWJpbGl0eUJhc2lzUG9pbnRzIjo1NDAwLCJncm93dGhFeHBlcmllbmNlIjoxMDR9LCJibG9jayI6eyJhYmlsaXR5QmFzaXNQb2ludHMiOjU1" +
            "MDAsImdyb3d0aEV4cGVyaWVuY2UiOjEwNX0sIm1vdmVtZW50Ijp7ImFiaWxpdHlCYXNpc1BvaW50cyI6NTYwMCwiZ3Jvd3RoRXhwZXJpZW5jZSI6MTA2fSwi" +
            "anVtcCI6eyJhYmlsaXR5QmFzaXNQb2ludHMiOjU3MDAsImdyb3d0aEV4cGVyaWVuY2UiOjEwN30sInN0YW1pbmEiOnsiYWJpbGl0eUJhc2lzUG9pbnRzIjo1" +
            "ODAwLCJncm93dGhFeHBlcmllbmNlIjoxMDh9fX0sInRlYW1JZCI6InRlYW0udW5pdmVyc2l0eS1hIiwicG90ZW50aWFsR3JhZGUiOiJiIiwiZmF0aWd1ZSI6" +
            "MjMsIm1pbmRzZXQiOjcyLCJjb2FjaFRydXN0Ijo2MSwib3BlcmF0aW9uUmVjZWlwdHMiOlt7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAw" +
            "MDAtMDAwMDAwMDAwMjAwIiwib3BlcmF0aW9uS2luZCI6ImNyZWF0ZV9jYXJlZXIiLCJ0YXJnZXQiOnsidHJ5b3V0U3RhZ2UiOjAsInRyeW91dE9jY3VycmVu" +
            "Y2VJZCI6bnVsbCwiY2hvaWNlSWQiOm51bGwsIndlZWtQbGFuSWQiOm51bGwsInNsb3RBY3Rpb25JZCI6bnVsbCwiYWN0aW9uT2NjdXJyZW5jZUlkIjpudWxs" +
            "LCJldmVudE9jY3VycmVuY2VJZCI6bnVsbCwib3B0aW9uSWQiOm51bGx9LCJpbnB1dEZpbmdlcnByaW50IjoiY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2Nj" +
            "Y2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjYyIsImFwcGxpZWRMaW5lYWdlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAw" +
            "MDAwMDMiLCJhcHBsaWVkUmV2aXNpb24iOjEsImNvbXBsZXRlZEF0VXRjTXMiOjMyMDAsIm91dGNvbWVLaW5kIjoiY2FyZWVyX2NyZWF0ZWQiLCJvdXRjb21l" +
            "U3VtbWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOltdLCJncm93dGhFeHBlcmllbmNlRGVsdGEiOm51bGwsImZhdGlndWVEZWx0YSI6bnVsbCwibWlu" +
            "ZHNldERlbHRhIjpudWxsLCJjb2FjaFRydXN0RGVsdGEiOm51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAw" +
            "MjAxIiwib3BlcmF0aW9uS2luZCI6ImNvbmZpcm1fdHJ5b3V0X3N0YWdlIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjoxLCJ0cnlvdXRPY2N1cnJlbmNlSWQi" +
            "OiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDEiLCJjaG9pY2VJZCI6InN0YWdlLTEtY2hvaWNlIiwid2Vla1BsYW5JZCI6bnVsbCwic2xv" +
            "dEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbH0sImlucHV0" +
            "RmluZ2VycHJpbnQiOiJkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkIiwiYXBwbGllZExp" +
            "bmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6MiwiY29tcGxldGVkQXRVdGNNcyI6MzIw" +
            "MSwib3V0Y29tZUtpbmQiOiJ0cnlvdXRfYWR2YW5jZWQiLCJvdXRjb21lU3VtbWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoi" +
            "c3RhZ2UtMS1wcmltYXJ5IiwicGVydHVyYmF0aW9uIjoxMH0seyJvdXRwdXRJZCI6InN0YWdlLTEtc2Vjb25kYXJ5IiwicGVydHVyYmF0aW9uIjotNX1dLCJn" +
            "cm93dGhFeHBlcmllbmNlRGVsdGEiOm51bGwsImZhdGlndWVEZWx0YSI6bnVsbCwibWluZHNldERlbHRhIjpudWxsLCJjb2FjaFRydXN0RGVsdGEiOm51bGx9" +
            "fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMjAyIiwib3BlcmF0aW9uS2luZCI6ImNvbmZpcm1fdHJ5b3V0X3N0" +
            "YWdlIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjoyLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDIi" +
            "LCJjaG9pY2VJZCI6InN0YWdlLTItY2hvaWNlIiwid2Vla1BsYW5JZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51" +
            "bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVl" +
            "ZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlZWVlIiwiYXBwbGllZExpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAw" +
            "MDAwMDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6MywiY29tcGxldGVkQXRVdGNNcyI6MzIwMiwib3V0Y29tZUtpbmQiOiJ0cnlvdXRfYWR2YW5jZWQiLCJvdXRj" +
            "b21lU3VtbWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOlt7Im91dHB1dElkIjoic3RhZ2UtMi1wcmltYXJ5IiwicGVydHVyYmF0aW9uIjoxMH0seyJv" +
            "dXRwdXRJZCI6InN0YWdlLTItc2Vjb25kYXJ5IiwicGVydHVyYmF0aW9uIjotNX1dLCJncm93dGhFeHBlcmllbmNlRGVsdGEiOm51bGwsImZhdGlndWVEZWx0" +
            "YSI6bnVsbCwibWluZHNldERlbHRhIjpudWxsLCJjb2FjaFRydXN0RGVsdGEiOm51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAw" +
            "MDAtMDAwMDAwMDAwMjAzIiwib3BlcmF0aW9uS2luZCI6ImNvbmZpcm1fdHJ5b3V0X3N0YWdlIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjozLCJ0cnlvdXRP" +
            "Y2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDMiLCJjaG9pY2VJZCI6InN0YWdlLTMtY2hvaWNlIiwid2Vla1BsYW5J" +
            "ZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51bGwsImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6" +
            "bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZm" +
            "IiwiYXBwbGllZExpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6NCwiY29tcGxldGVk" +
            "QXRVdGNNcyI6MzIwMywib3V0Y29tZUtpbmQiOiJ0cnlvdXRfYWR2YW5jZWQiLCJvdXRjb21lU3VtbWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOlt7" +
            "Im91dHB1dElkIjoic3RhZ2UtMy1wcmltYXJ5IiwicGVydHVyYmF0aW9uIjoxMH0seyJvdXRwdXRJZCI6InN0YWdlLTMtc2Vjb25kYXJ5IiwicGVydHVyYmF0" +
            "aW9uIjotNX1dLCJncm93dGhFeHBlcmllbmNlRGVsdGEiOm51bGwsImZhdGlndWVEZWx0YSI6bnVsbCwibWluZHNldERlbHRhIjpudWxsLCJjb2FjaFRydXN0" +
            "RGVsdGEiOm51bGx9fSx7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMjEwIiwib3BlcmF0aW9uS2luZCI6ImNvbmZp" +
            "cm1fd2Vla19wbGFuIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjowLCJ0cnlvdXRPY2N1cnJlbmNlSWQiOm51bGwsImNob2ljZUlkIjpudWxsLCJ3ZWVrUGxh" +
            "bklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDEwIiwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51bGws" +
            "ImV2ZW50T2NjdXJyZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh" +
            "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhIiwiYXBwbGllZExpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAw" +
            "MDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6NSwiY29tcGxldGVkQXRVdGNNcyI6MzIxMCwib3V0Y29tZUtpbmQiOiJ3ZWVrX3BsYW5fY29uZmlybWVkIiwib3V0" +
            "Y29tZVN1bW1hcnkiOnsidHJ5b3V0UmVzb2x2ZWRPdXRwdXRzIjpbXSwiZ3Jvd3RoRXhwZXJpZW5jZURlbHRhIjpudWxsLCJmYXRpZ3VlRGVsdGEiOm51bGws" +
            "Im1pbmRzZXREZWx0YSI6bnVsbCwiY29hY2hUcnVzdERlbHRhIjpudWxsfX0seyJvcGVyYXRpb25JZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAw" +
            "MDAwMDIxMSIsIm9wZXJhdGlvbktpbmQiOiJleGVjdXRlX3dlZWtfYWN0aW9uIiwidGFyZ2V0Ijp7InRyeW91dFN0YWdlIjowLCJ0cnlvdXRPY2N1cnJlbmNl" +
            "SWQiOm51bGwsImNob2ljZUlkIjpudWxsLCJ3ZWVrUGxhbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDEwIiwic2xvdEFjdGlvbklk" +
            "IjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDExIiwiYWN0aW9uT2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAw" +
            "MDAwMDAwMDQxIiwiZXZlbnRPY2N1cnJlbmNlSWQiOm51bGwsIm9wdGlvbklkIjpudWxsfSwiaW5wdXRGaW5nZXJwcmludCI6ImJiYmJiYmJiYmJiYmJiYmJi" +
            "YmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmIiLCJhcHBsaWVkTGluZWFnZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAw" +
            "MDAtMDAwMDAwMDAwMDAzIiwiYXBwbGllZFJldmlzaW9uIjo2LCJjb21wbGV0ZWRBdFV0Y01zIjozMjExLCJvdXRjb21lS2luZCI6InNsb3RfY29tcGxldGVk" +
            "Iiwib3V0Y29tZVN1bW1hcnkiOnsidHJ5b3V0UmVzb2x2ZWRPdXRwdXRzIjpbXSwiZ3Jvd3RoRXhwZXJpZW5jZURlbHRhIjp7InNwaWtlIjoxLCJzZXJ2ZSI6" +
            "MTEsInJlY2VwdGlvbiI6MjEsImRlZmVuc2UiOjMxLCJibG9jayI6NDEsIm1vdmVtZW50Ijo1MSwianVtcCI6NjEsInN0YW1pbmEiOjcxfSwiZmF0aWd1ZURl" +
            "bHRhIjo0LCJtaW5kc2V0RGVsdGEiOjEsImNvYWNoVHJ1c3REZWx0YSI6Mn19LHsib3BlcmF0aW9uSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAw" +
            "MDAwMDAyMTIiLCJvcGVyYXRpb25LaW5kIjoicmVzb2x2ZV9ldmVudF9jaG9pY2UiLCJ0YXJnZXQiOnsidHJ5b3V0U3RhZ2UiOjAsInRyeW91dE9jY3VycmVu" +
            "Y2VJZCI6bnVsbCwiY2hvaWNlSWQiOm51bGwsIndlZWtQbGFuSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMTAiLCJzbG90QWN0aW9u" +
            "SWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMTEiLCJhY3Rpb25PY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w" +
            "MDAwMDAwMDAwNDEiLCJldmVudE9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDA1MCIsIm9wdGlvbklkIjoiYWNjZXB0" +
            "In0sImlucHV0RmluZ2VycHJpbnQiOiJjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjIiwi" +
            "YXBwbGllZExpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6NywiY29tcGxldGVkQXRV" +
            "dGNNcyI6MzIxMiwib3V0Y29tZUtpbmQiOiJldmVudF9jaG9pY2VfYXBwbGllZCIsIm91dGNvbWVTdW1tYXJ5Ijp7InRyeW91dFJlc29sdmVkT3V0cHV0cyI6" +
            "W10sImdyb3d0aEV4cGVyaWVuY2VEZWx0YSI6eyJzcGlrZSI6MTAsInNlcnZlIjoyMCwicmVjZXB0aW9uIjozMCwiZGVmZW5zZSI6NDAsImJsb2NrIjo1MCwi" +
            "bW92ZW1lbnQiOjYwLCJqdW1wIjo3MCwic3RhbWluYSI6ODB9LCJmYXRpZ3VlRGVsdGEiOjUsIm1pbmRzZXREZWx0YSI6MTAsImNvYWNoVHJ1c3REZWx0YSI6" +
            "LTJ9fV19";

        private const string PreStage4GoldenBase64 =
            "eyJ2ZXJzaW9ucyI6eyJzY2hlbWFWZXJzaW9uIjoxLCJjb250ZW50VmVyc2lvbiI6MSwicnVsZXNldFZlcnNpb24iOjEsImNhcmVl" +
            "clJhbmRvbUFsZ29yaXRobVZlcnNpb24iOjF9LCJpZGVudGl0eSI6eyJwcm9maWxlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAw" +
            "MC0wMDAwMDAwMDAwMDEiLCJzYXZlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDIiLCJsaW5lYWdlSWQi" +
            "OiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDMiLCJyZXZpc2lvbiI6MSwicmVzdG9yZWRGcm9tVmVyc2lvblRv" +
            "a2VuIjpudWxsLCJjcmVhdGVkQXRVdGNNcyI6MCwidXBkYXRlZEF0VXRjTXMiOjkwMDcxOTkyNTQ3NDA5OTF9LCJpbnRlZ3JpdHki" +
            "Onsic25hcHNob3RIYXNoIjoiMjFlOTM1ZTk4YTRmZGM2ZjMxNThmMjJiNWFkYjExNWY1ZTBlYWI5NGNlNzU1YTY0YmE0ODgyZDY3" +
            "NmI0YTk4YSJ9LCJjYXJlZXJTZWVkIjoiMDAwMTAyMDMwNDA1MDYwNzA4MDkwYTBiMGMwZDBlMGYxMDExMTIxMzE0MTUxNjE3MTgx" +
            "OTFhMWIxYzFkMWUxZiIsImNhcmVlck5hbWUiOiJFc2NhcGVzOlwiXFwvIENvbnRyb2xzOlx1MDAwMFx1MDAwMVx1MDAwMlx1MDAw" +
            "M1x1MDAwNFx1MDAwNVx1MDAwNlx1MDAwN1xiXHRcblx1MDAwYlxmXHJcdTAwMGVcdTAwMGZcdTAwMTBcdTAwMTFcdTAwMTJcdTAw" +
            "MTNcdTAwMTRcdTAwMTVcdTAwMTZcdTAwMTdcdTAwMThcdTAwMTlcdTAwMWFcdTAwMWJcdTAwMWNcdTAwMWRcdTAwMWVcdTAwMWYg" +
            "VW5pY29kZTrpm6rwn5iAIMOpIGXMgSIsInBsYXllckRyYWZ0Ijp7InBsYXllcklkIjoicGxheWVyLmFscGhhIiwiZGlzcGxheU5h" +
            "bWUiOiJQbGF5ZXIg6Zuq8J+YgCIsImplcnNleU51bWJlciI6MTJ9LCJvbmJvYXJkaW5nIjp7InN0YWdlcyI6W3sic3RhZ2VOdW1i" +
            "ZXIiOjEsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDEwMSIsInJhbmRvbVZlcnNpb24i" +
            "OjEsImNob2ljZUlkIjpudWxsLCJyZXNvbHZlZE91dHB1dHMiOltdfSx7InN0YWdlTnVtYmVyIjoyLCJvY2N1cnJlbmNlSWQiOiIw" +
            "MDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDIiLCJyYW5kb21WZXJzaW9uIjoxLCJjaG9pY2VJZCI6bnVsbCwicmVz" +
            "b2x2ZWRPdXRwdXRzIjpbXX0seyJzdGFnZU51bWJlciI6Mywib2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt" +
            "MDAwMDAwMDAwMTAzIiwicmFuZG9tVmVyc2lvbiI6MSwiY2hvaWNlSWQiOm51bGwsInJlc29sdmVkT3V0cHV0cyI6W119XSwibmV4" +
            "dFN0YWdlTnVtYmVyIjoxLCJpc0Zvcm1hbGx5RW5yb2xsZWQiOmZhbHNlfSwicHJvZ3Jlc3Npb24iOnsia2luZCI6ImNhcmVlcl9j" +
            "cmVhdGVkIiwicGhhc2UiOiJ1bml2ZXJzaXR5IiwidHJ5b3V0U3RhZ2UiOjAsIndlZWtQbGFuIjpudWxsLCJuZXh0U2xvdE51bWJl" +
            "ciI6MCwicGVuZGluZ0V2ZW50IjpudWxsfSwicGxheWVyIjpudWxsLCJ0ZWFtSWQiOm51bGwsInBvdGVudGlhbEdyYWRlIjpudWxs" +
            "LCJmYXRpZ3VlIjpudWxsLCJtaW5kc2V0IjpudWxsLCJjb2FjaFRydXN0IjpudWxsLCJvcGVyYXRpb25SZWNlaXB0cyI6W3sib3Bl" +
            "cmF0aW9uSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAyMDAiLCJvcGVyYXRpb25LaW5kIjoiY3JlYXRlX2Nh" +
            "cmVlciIsInRhcmdldCI6eyJ0cnlvdXRTdGFnZSI6MCwidHJ5b3V0T2NjdXJyZW5jZUlkIjpudWxsLCJjaG9pY2VJZCI6bnVsbCwi" +
            "d2Vla1BsYW5JZCI6bnVsbCwic2xvdEFjdGlvbklkIjpudWxsLCJhY3Rpb25PY2N1cnJlbmNlSWQiOm51bGwsImV2ZW50T2NjdXJy" +
            "ZW5jZUlkIjpudWxsLCJvcHRpb25JZCI6bnVsbH0sImlucHV0RmluZ2VycHJpbnQiOiJhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh" +
            "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhIiwiYXBwbGllZExpbmVhZ2VJZCI6IjAwMDAwMDAwLTAwMDAt" +
            "MDAwMC0wMDAwLTAwMDAwMDAwMDAwMyIsImFwcGxpZWRSZXZpc2lvbiI6MSwiY29tcGxldGVkQXRVdGNNcyI6OTAwNzE5OTI1NDc0" +
            "MDk5MSwib3V0Y29tZUtpbmQiOiJjYXJlZXJfY3JlYXRlZCIsIm91dGNvbWVTdW1tYXJ5Ijp7InRyeW91dFJlc29sdmVkT3V0cHV0" +
            "cyI6W10sImdyb3d0aEV4cGVyaWVuY2VEZWx0YSI6bnVsbCwiZmF0aWd1ZURlbHRhIjpudWxsLCJtaW5kc2V0RGVsdGEiOm51bGws" +
            "ImNvYWNoVHJ1c3REZWx0YSI6bnVsbH19XX0=";

        private const string UnsupportedV1GoldenBase64 =
            "eyJ2ZXJzaW9ucyI6eyJzY2hlbWFWZXJzaW9uIjoxLCJjb250ZW50VmVyc2lvbiI6MSwicnVsZXNldFZlcnNpb24iOjEsImNhcmVlclJhbmRvbUFsZ29yaXRobVZlcnNpb24iOjF9LCJpZGVudGl0eSI6eyJwcm9maWxlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJzYXZlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDIiLCJsaW5lYWdlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDMiLCJyZXZpc2lvbiI6MSwicmVzdG9yZWRGcm9tVmVyc2lvblRva2VuIjpudWxsLCJjcmVhdGVkQXRVdGNNcyI6MCwidXBkYXRlZEF0VXRjTXMiOjkwMDcxOTkyNTQ3NDA5OTF9LCJpbnRlZ3JpdHkiOnsic25hcHNob3RIYXNoIjoiZDllOTQ2NGIwZWVlZWEzYzg0OGVmZmY5NTIyZTJkNDFlM2MxNGRiNDBkZTJjN2RiNDBiMmRhYWE1Mzc4ZDIzNyJ9LCJjYXJlZXJTZWVkIjoiMDAwMTAyMDMwNDA1MDYwNzA4MDkwYTBiMGMwZDBlMGYxMDExMTIxMzE0MTUxNjE3MTgxOTFhMWIxYzFkMWUxZiIsImNhcmVlck5hbWUiOiJFc2NhcGVzOlwiXFwvIENvbnRyb2xzOlx1MDAwMFx1MDAwMVx1MDAwMlx1MDAwM1x1MDAwNFx1MDAwNVx1MDAwNlx1MDAwN1xiXHRcblx1MDAwYlxmXHJcdTAwMGVcdTAwMGZcdTAwMTBcdTAwMTFcdTAwMTJcdTAwMTNcdTAwMTRcdTAwMTVcdTAwMTZcdTAwMTdcdTAwMThcdTAwMTlcdTAwMWFcdTAwMWJcdTAwMWNcdTAwMWRcdTAwMWVcdTAwMWYgVW5pY29kZTrpm6rwn5iAIMOpIGXMgSIsInBsYXllckRyYWZ0Ijp7InBsYXllcklkIjoicGxheWVyLmFscGhhIiwiZGlzcGxheU5hbWUiOiJQbGF5ZXIg6Zuq8J+YgCIsImplcnNleU51bWJlciI6MTJ9LCJvbmJvYXJkaW5nIjp7InN0YWdlcyI6W3sic3RhZ2VOdW1iZXIiOjEsIm9jY3VycmVuY2VJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDEwMSIsInJhbmRvbVZlcnNpb24iOjEsImNob2ljZUlkIjpudWxsLCJyZXNvbHZlZE91dHB1dHMiOltdfSx7InN0YWdlTnVtYmVyIjoyLCJvY2N1cnJlbmNlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAxMDIiLCJyYW5kb21WZXJzaW9uIjoxLCJjaG9pY2VJZCI6bnVsbCwicmVzb2x2ZWRPdXRwdXRzIjpbXX0seyJzdGFnZU51bWJlciI6Mywib2NjdXJyZW5jZUlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTAzIiwicmFuZG9tVmVyc2lvbiI6MSwiY2hvaWNlSWQiOm51bGwsInJlc29sdmVkT3V0cHV0cyI6W119XSwibmV4dFN0YWdlTnVtYmVyIjoxLCJpc0Zvcm1hbGx5RW5yb2xsZWQiOmZhbHNlfSwicHJvZ3Jlc3Npb24iOnsia2luZCI6ImNhcmVlcl9jcmVhdGVkIiwicGhhc2UiOiJ1bml2ZXJzaXR5IiwidHJ5b3V0U3RhZ2UiOjAsIndlZWtQbGFuIjpudWxsLCJuZXh0U2xvdE51bWJlciI6MCwicGVuZGluZ0V2ZW50IjpudWxsfSwidHJhaW5pbmdFbXBoYXNlcyI6W10sInBsYXllciI6bnVsbCwidGVhbUlkIjpudWxsLCJwb3RlbnRpYWxHcmFkZSI6bnVsbCwiZmF0aWd1ZSI6bnVsbCwibWluZHNldCI6bnVsbCwiY29hY2hUcnVzdCI6bnVsbCwib3BlcmF0aW9uUmVjZWlwdHMiOlt7Im9wZXJhdGlvbklkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMjAwIiwib3BlcmF0aW9uS2luZCI6ImNyZWF0ZV9jYXJlZXIiLCJ0YXJnZXQiOnsidHJ5b3V0U3RhZ2UiOjAsInRyeW91dE9jY3VycmVuY2VJZCI6bnVsbCwiY2hvaWNlSWQiOm51bGwsIndlZWtQbGFuSWQiOm51bGwsInNsb3RBY3Rpb25JZCI6bnVsbCwiYWN0aW9uT2NjdXJyZW5jZUlkIjpudWxsLCJldmVudE9jY3VycmVuY2VJZCI6bnVsbCwib3B0aW9uSWQiOm51bGx9LCJpbnB1dEZpbmdlcnByaW50IjoiYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYSIsImFwcGxpZWRMaW5lYWdlSWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDMiLCJhcHBsaWVkUmV2aXNpb24iOjEsImNvbXBsZXRlZEF0VXRjTXMiOjkwMDcxOTkyNTQ3NDA5OTEsIm91dGNvbWVLaW5kIjoiY2FyZWVyX2NyZWF0ZWQiLCJvdXRjb21lU3VtbWFyeSI6eyJ0cnlvdXRSZXNvbHZlZE91dHB1dHMiOltdLCJncm93dGhFeHBlcmllbmNlRGVsdGEiOm51bGwsImZhdGlndWVEZWx0YSI6bnVsbCwibWluZHNldERlbHRhIjpudWxsLCJjb2FjaFRydXN0RGVsdGEiOm51bGx9fV19";

        [Test]
        public void OrdinarySchemaV2_WritesRequiredNullAndEmptyLifecycleBranchesInRootOrder()
        {
            var candidate = CareerPersistenceTestData.CreatedSnapshot(
                new ProfileId(Guid.Parse("11111111-1111-1111-1111-111111111111")),
                new SaveId(Guid.Parse("22222222-2222-2222-2222-222222222222")),
                new LineageId(Guid.Parse("33333333-3333-3333-3333-333333333333")));
            var document = CareerSaveSnapshotMapper.ToDocument(candidate);
            var json = Encoding.UTF8.GetString(
                CareerSaveJsonCodec.Serialize(CareerSaveJsonCodec.Seal(candidate)));

            Assert.That(document.pendingMatch, Is.Null);
            Assert.That(document.matchHistory, Is.Empty);
            Assert.That(document.settlementReceipts, Is.Empty);
            Assert.That(document.progression.matchSessionId, Is.Null);
            Assert.That(json, Does.Contain(
                "\"progression\":{\"kind\":\"career_created\",\"phase\":\"university\"," +
                "\"tryoutStage\":0,\"weekPlan\":null,\"nextSlotNumber\":0," +
                "\"pendingEvent\":null,\"matchSessionId\":null}"));
            Assert.That(json, Does.Contain(
                "\"trainingEmphases\":[],\"pendingMatch\":null,\"player\":null"));
            Assert.That(json, Does.Contain(
                "\"coachTrust\":null,\"matchHistory\":[],\"operationReceipts\":"));
            Assert.That(json, Does.EndWith("\"settlementReceipts\":[]}"));
        }

        [Test]
        public void AwaitingMatchSchemaV2_CanonicalCodecRoundTripPreservesRawContextAndShape()
        {
            var source = CareerSaveV2LifecycleTestData.AwaitingMatchSnapshot();
            var sealedSnapshot = CareerSaveJsonCodec.Seal(source);
            var bytes = CareerSaveJsonCodec.Serialize(sealedSnapshot);
            var restored = CareerSaveJsonCodec.Deserialize(bytes);

            Assert.That(restored.PendingMatch, Is.Not.Null);
            Assert.That(
                restored.PendingMatch.CanonicalContextUtf8,
                Is.EqualTo(source.PendingMatch.CanonicalContextUtf8));
            Assert.That(
                CareerSaveJsonCodec.Serialize(restored),
                Is.EqualTo(bytes));
            var json = Encoding.UTF8.GetString(bytes);
            Assert.That(json, Does.Contain(
                "\"pendingMatch\":{\"sessionId\":"));
            Assert.That(json, Does.Contain(
                "\"orderedPlayerIds\":[\"player.home.opposite\"," +
                "\"player.career.protagonist\""));
            Assert.That(json, Does.Contain(
                "\"operationKind\":\"create_pending_match\""));
            Assert.That(json, Does.Contain(
                "\"outcomeKind\":\"pending_match_created\""));
        }

        [Test]
        public void SettledSchemaV2_CanonicalCodecRoundTripPreservesRawEvidenceAndSummary()
        {
            var source = CareerSaveV2LifecycleTestData.SettledSnapshot();
            var sealedSnapshot = CareerSaveJsonCodec.Seal(source);
            var bytes = CareerSaveJsonCodec.Serialize(sealedSnapshot);
            var restored = CareerSaveJsonCodec.Deserialize(bytes);

            Assert.That(restored.PendingMatch, Is.Null);
            Assert.That(restored.MatchHistory, Has.Count.EqualTo(1));
            Assert.That(restored.SettlementReceipts, Has.Count.EqualTo(1));
            Assert.That(
                restored.MatchHistory[0].CanonicalContextUtf8,
                Is.EqualTo(source.MatchHistory[0].CanonicalContextUtf8));
            Assert.That(
                restored.MatchHistory[0].CanonicalResultUtf8,
                Is.EqualTo(source.MatchHistory[0].CanonicalResultUtf8));
            Assert.That(
                restored.MatchHistory[0].SettlementSummary,
                Is.EqualTo(source.MatchHistory[0].SettlementSummary));
            Assert.That(CareerSaveJsonCodec.Serialize(restored), Is.EqualTo(bytes));
            var json = Encoding.UTF8.GetString(bytes);
            Assert.That(json, Does.Contain(
                "\"settlementSummary\":{\"sets\":[{\"setNumber\":1,"));
            Assert.That(json, Does.Contain(
                "\"protagonistFacts\":{\"spike\":{\"attempts\":"));
            Assert.That(json, Does.EndWith("}]}"));
        }

        [Test]
        public void GoldenSnapshot_HasIndependentCanonicalBytesAndHash()
        {
            var candidate = CreateGoldenCandidate();

            var sealedSnapshot = CareerSaveJsonCodec.Seal(candidate);
            var actualBytes = CareerSaveJsonCodec.Serialize(sealedSnapshot);
            var actualBase64 = Convert.ToBase64String(actualBytes);

            Assert.That(
                actualBase64,
                Is.EqualTo(V2GoldenBase64),
                "Replace V2GoldenBase64 with: " + actualBase64 +
                "\nReplace V2GoldenHash with: " +
                sealedSnapshot.Identity.SnapshotHash.Value);
            Assert.That(
                CareerSaveJsonCodec.ComputeSnapshotHash(candidate).Value,
                Is.EqualTo(V2GoldenHash));
            Assert.That(sealedSnapshot.Identity.SnapshotHash.Value, Is.EqualTo(V2GoldenHash));
            Assert.That(actualBytes[0], Is.EqualTo((byte)'{'));
            Assert.That(candidate.Identity.SnapshotHash.Value, Is.EqualTo(new string('0', 64)));

            var json = Encoding.UTF8.GetString(actualBytes);
            StringAssert.Contains("\\u0000\\u0001\\u0002", json);
            StringAssert.Contains("\\b\\t\\n\\u000b\\f\\r", json);
            StringAssert.Contains("\\u001d\\u001e\\u001f", json);
            StringAssert.Contains("Unicode:雪" + char.ConvertFromUtf32(0x1f600), json);
            StringAssert.Contains("é e\u0301", json);
        }

        [Test]
        public void GoldenSnapshot_StrictlyDeserializesToTheDomainModel()
        {
            var restored = CareerSaveJsonCodec.Deserialize(
                Convert.FromBase64String(V2GoldenBase64));

            Assert.That(restored.Identity.SnapshotHash.Value, Is.EqualTo(V2GoldenHash));
            Assert.That(restored.Identity.RestoredFromVersionToken, Is.Null);
            Assert.That(restored.Identity.UpdatedAtUtcMs, Is.EqualTo(MaximumIJsonSafeInteger));
            Assert.That(restored.CareerName, Is.EqualTo(SpecialCareerName()));
            Assert.That(restored.Onboarding.Stages[0].ResolvedOutputs, Is.Empty);
            Assert.That(restored.Player, Is.Null);
            Assert.That(restored.TeamId, Is.Null);
        }

        [Test]
        public void UnsupportedV1Golden_IsRejectedBeforeBodyMappingWithoutChangingItsBytes()
        {
            var bytes = UnsupportedV1GoldenBytes();
            var copy = (byte[])bytes.Clone();

            var exception = Assert.Throws<CareerSaveVersionNotSupportedException>(
                () => CareerSaveJsonCodec.Deserialize(bytes));

            Assert.That(exception.ObservedSchemaVersion, Is.EqualTo(1));
            Assert.That(bytes, Is.EqualTo(copy));
            Assert.That(
                Encoding.UTF8.GetString(bytes),
                Does.Contain("\"snapshotHash\":\"" + UnsupportedV1GoldenHash + "\""));
        }

        internal static byte[] UnsupportedV1GoldenBytes()
        {
            return Convert.FromBase64String(UnsupportedV1GoldenBase64);
        }

        [Test]
        public void UnsupportedSchema3Golden_IsRejectedBeforeBodyMappingWithoutChangingItsBytes()
        {
            var bytes = UnsupportedSchema3GoldenBytes();
            var copy = (byte[])bytes.Clone();

            var exception = Assert.Throws<CareerSaveVersionNotSupportedException>(
                () => CareerSaveJsonCodec.Deserialize(bytes));

            Assert.That(exception.ObservedSchemaVersion, Is.EqualTo(3));
            Assert.That(bytes, Is.EqualTo(copy));
        }

        internal static byte[] UnsupportedSchema3GoldenBytes()
        {
            var json = Encoding.UTF8.GetString(Convert.FromBase64String(V2GoldenBase64));
            return Encoding.UTF8.GetBytes(
                json.Replace("\"schemaVersion\":2", "\"schemaVersion\":3"));
        }

        [Test]
        public void Deserialize_ReportsSchemaV2WhenTheRootPropertySetIsIncomplete()
        {
            var exception = Assert.Throws<FormatException>(() =>
                CareerSaveJsonCodec.Deserialize(Encoding.UTF8.GetBytes(
                    "{\"versions\":{\"schemaVersion\":2,\"contentVersion\":1," +
                    "\"rulesetVersion\":1,\"contractVersion\":2," +
                    "\"careerRandomAlgorithmVersion\":1}}")));

            Assert.That(exception.Message, Does.Contain("Schema V2"));
            Assert.That(exception.Message, Does.Not.Contain("Schema V1"));
        }

        [Test]
        public void Deserialize_ReportsSchemaV2WhenARequiredRootPropertyIsRenamed()
        {
            var json = Encoding.UTF8.GetString(Convert.FromBase64String(V2GoldenBase64))
                .Replace("\"careerName\":", "\"futureCareerName\":");

            var exception = Assert.Throws<FormatException>(() =>
                CareerSaveJsonCodec.Deserialize(Encoding.UTF8.GetBytes(json)));

            Assert.That(exception.Message, Does.Contain("Schema V2"));
            Assert.That(exception.Message, Does.Not.Contain("Schema V1"));
        }

        [Test]
        public void SnapshotMapper_ReportsSchemaV2WhenOnboardingStageCountIsInvalid()
        {
            var document = CareerSaveSnapshotMapper.ToDocument(CreateGoldenCandidate());
            document.onboarding.stages = new[]
            {
                document.onboarding.stages[0],
                document.onboarding.stages[1]
            };

            var exception = Assert.Throws<ArgumentException>(() =>
                CareerSaveSnapshotMapper.ToDomain(document));

            Assert.That(exception.Message, Does.Contain("Schema V2"));
            Assert.That(exception.Message, Does.Not.Contain("Schema V1"));
        }

        [Test]
        public void SnapshotMapper_ReportsSchemaV2WhenPendingEventOptionCountIsInvalid()
        {
            var document = CareerSaveSnapshotMapper.ToDocument(
                CreateFullCandidate(false));
            document.progression.pendingEvent.options = new[]
            {
                document.progression.pendingEvent.options[0]
            };

            var exception = Assert.Throws<ArgumentException>(() =>
                CareerSaveSnapshotMapper.ToDomain(document));

            Assert.That(exception.Message, Does.Contain("schema V2"));
            Assert.That(exception.Message, Does.Not.Contain("schema V1"));
        }

        [Test]
        public void AwaitingLifecycleGolden_LocksCanonicalBytesBase64AndHash()
        {
            var sealedSnapshot = CareerSaveJsonCodec.Seal(
                CareerSaveV2LifecycleTestData.AwaitingMatchSnapshot());
            var bytes = CareerSaveJsonCodec.Serialize(sealedSnapshot);
            var base64 = Convert.ToBase64String(bytes);

            Assert.That(
                base64,
                Is.EqualTo(LifecycleGoldenBase64),
                "Replace LifecycleGoldenBase64 with: " + base64 +
                "\nReplace LifecycleGoldenHash with: " +
                sealedSnapshot.Identity.SnapshotHash.Value);
            Assert.That(
                sealedSnapshot.Identity.SnapshotHash.Value,
                Is.EqualTo(LifecycleGoldenHash));
            Assert.That(
                CareerSaveJsonCodec.Deserialize(bytes).PendingMatch.CanonicalContextUtf8,
                Is.EqualTo(CareerSaveV2LifecycleTestData.ContextBytes()));
        }

        [Test]
        public void ExecutedSnapshot_LocksActionContentAndNonEmptyEmphasisHashAndRoundTrips()
        {
            var candidate = CreateExecutedGoldenCandidate(
                "week_action.specialized.spike");
            var sealedSnapshot = CareerSaveJsonCodec.Seal(candidate);
            var actualBytes = CareerSaveJsonCodec.Serialize(sealedSnapshot);
            Assert.That(
                sealedSnapshot.Identity.SnapshotHash.Value,
                Is.EqualTo(ExecutedGoldenHash));

            var restored = CareerSaveJsonCodec.Deserialize(
                actualBytes);
            Assert.That(restored.Progression.Kind, Is.EqualTo(CareerProgressionKind.Planned));
            Assert.That(restored.Progression.NextSlotNumber, Is.EqualTo(2));
            Assert.That(
                restored.Progression.WeekPlan.Slots[0].ContentId,
                Is.EqualTo("week_action.specialized.spike"));
            Assert.That(restored.TrainingEmphases.Contributions.Count, Is.EqualTo(1));
            Assert.That(
                restored.TrainingEmphases.Contributions[0].Direction,
                Is.EqualTo(CareerTrainingDirection.Spike));
            Assert.That(
                restored.TrainingEmphases.Contributions[0].BonusBasisPoints,
                Is.EqualTo(1000));
        }

        [Test]
        public void SnapshotHash_ChangesForValidActionContentAndDerivedEmphasis()
        {
            var spike = CreateExecutedGoldenCandidate(
                "week_action.specialized.spike");
            var serve = CreateExecutedGoldenCandidate(
                "week_action.specialized.serve");

            Assert.That(
                spike.TrainingEmphases.Contributions[0].Direction,
                Is.EqualTo(CareerTrainingDirection.Spike));
            Assert.That(
                serve.TrainingEmphases.Contributions[0].Direction,
                Is.EqualTo(CareerTrainingDirection.Serve));
            Assert.That(
                CareerSaveJsonCodec.ComputeSnapshotHash(serve),
                Is.Not.EqualTo(CareerSaveJsonCodec.ComputeSnapshotHash(spike)));
        }

        [Test]
        public void SnapshotHash_OrdinaryStateChangesForAValidTopLevelMutation()
        {
            var first = CreateGoldenCandidate(careerName: "Ordinary A");
            var second = CreateGoldenCandidate(careerName: "Ordinary B");

            Assert.That(
                CareerSaveJsonCodec.ComputeSnapshotHash(second),
                Is.Not.EqualTo(CareerSaveJsonCodec.ComputeSnapshotHash(first)));
        }

        [Test]
        public void SnapshotHash_AwaitingStateIncludesPendingMatchBranch()
        {
            var document = CareerSaveSnapshotMapper.ToDocument(
                CareerSaveV2LifecycleTestData.AwaitingMatchSnapshot());
            var baseline = ComputeDocumentHash(document);

            document.pendingMatch.competitionId += ".changed";

            Assert.That(ComputeDocumentHash(document), Is.Not.EqualTo(baseline));
        }

        [Test]
        public void SnapshotHash_SettledStateIncludesHistoryAndSettlementBranches()
        {
            var document = CareerSaveSnapshotMapper.ToDocument(
                CareerSaveV2LifecycleTestData.SettledSnapshot());
            var baseline = ComputeDocumentHash(document);
            document.matchHistory[0].settledAtUtcMs += 1;
            var changedHistory = ComputeDocumentHash(document);
            document.matchHistory[0].settledAtUtcMs -= 1;
            document.settlementReceipts[0].settledAtUtcMs += 1;
            var changedSettlement = ComputeDocumentHash(document);

            Assert.That(changedHistory, Is.Not.EqualTo(baseline));
            Assert.That(changedSettlement, Is.Not.EqualTo(baseline));
            Assert.That(changedSettlement, Is.Not.EqualTo(changedHistory));
        }

        [Test]
        public void PreStage4IncompleteV1GoldenRequiresSaveRecreation()
        {
            Assert.That(
                () => CareerSaveJsonCodec.Deserialize(
                    Convert.FromBase64String(PreStage4GoldenBase64)),
                Throws.TypeOf<CareerSaveVersionNotSupportedException>());
        }

        [TestCase(false)]
        [TestCase(true)]
        public void FullSchemaRoundTrip_PreservesNestedStateAndRestoreProvenance(
            bool eventAlreadyResolved)
        {
            var source = CreateFullCandidate(eventAlreadyResolved);

            var sealedSnapshot = CareerSaveJsonCodec.Seal(source);
            var bytes = CareerSaveJsonCodec.Serialize(sealedSnapshot);
            var restored = CareerSaveJsonCodec.Deserialize(bytes);

            Assert.That(restored.Identity.SnapshotHash, Is.EqualTo(sealedSnapshot.Identity.SnapshotHash));
            Assert.That(restored.Identity.RestoredFromVersionToken.HasValue, Is.True);
            Assert.That(
                restored.Identity.RestoredFromVersionToken.Value.LineageId,
                Is.EqualTo(new LineageId(GuidValue(4))));
            Assert.That(restored.Player.Attributes.Stamina.GrowthExperience, Is.EqualTo(108));
            Assert.That(restored.OperationReceipts.Count, Is.EqualTo(eventAlreadyResolved ? 7 : 6));

            if (eventAlreadyResolved)
            {
                Assert.That(restored.Progression.Kind, Is.EqualTo(CareerProgressionKind.Planned));
                Assert.That(restored.Progression.PendingEvent, Is.Null);
                Assert.That(
                    restored.OperationReceipts[6].OutcomeSummary.CoachTrustDelta,
                    Is.EqualTo(-2));
            }
            else
            {
                Assert.That(
                    restored.Progression.Kind,
                    Is.EqualTo(CareerProgressionKind.AwaitingEventChoice));
                Assert.That(restored.Progression.PendingEvent.Options.Count, Is.EqualTo(2));
                Assert.That(
                    restored.Progression.PendingEvent.Options[0].GrowthExperienceDelta.Stamina,
                    Is.EqualTo(80));
            }
        }

        [Test]
        public void Serialize_RejectsAnUnsealedSnapshot()
        {
            Assert.That(
                () => CareerSaveJsonCodec.Serialize(CreateGoldenCandidate()),
                Throws.InvalidOperationException);
        }

        [Test]
        public void SnapshotHash_ExcludesOnlyTheHashFieldItself()
        {
            var first = CareerSaveJsonCodec.ComputeSnapshotHash(
                CreateGoldenCandidate('0'));
            var sameContentWithDifferentStoredHash = CareerSaveJsonCodec.ComputeSnapshotHash(
                CreateGoldenCandidate('f'));
            var changedDisplayContent = CareerSaveJsonCodec.ComputeSnapshotHash(
                CreateGoldenCandidate('0', SpecialCareerName() + " changed"));

            Assert.That(sameContentWithDifferentStoredHash, Is.EqualTo(first));
            Assert.That(changedDisplayContent, Is.Not.EqualTo(first));
        }

        [TestCase("duplicate")]
        [TestCase("unknown")]
        [TestCase("missing")]
        [TestCase("leading_zero")]
        [TestCase("negative_zero")]
        [TestCase("floating_point")]
        [TestCase("scientific_notation")]
        [TestCase("plus_sign")]
        [TestCase("too_large")]
        [TestCase("too_small")]
        [TestCase("trailing_token")]
        [TestCase("lone_surrogate")]
        [TestCase("raw_control")]
        [TestCase("whitespace")]
        [TestCase("property_order")]
        [TestCase("escaped_slash")]
        [TestCase("uppercase_unicode_escape")]
        [TestCase("long_control_escape")]
        [TestCase("noncanonical_unicode_escape")]
        [TestCase("noncanonical_surrogate_escape")]
        [TestCase("tampered_value")]
        [TestCase("missing_hash")]
        public void Deserialize_RejectsMalformedNoncanonicalOrCorruptDocuments(string mutation)
        {
            var json = Encoding.UTF8.GetString(Convert.FromBase64String(V2GoldenBase64));

            switch (mutation)
            {
                case "duplicate":
                    json = json.Replace(
                        "\"careerSeed\":",
                        "\"careerSeed\":\"" + SeedHex() + "\",\"careerSeed\":");
                    break;
                case "unknown":
                    json = "{\"unknown\":null," + json.Substring(1);
                    break;
                case "missing":
                    json = json.Replace("\"coachTrust\":null,", string.Empty);
                    break;
                case "leading_zero":
                    json = json.Replace(
                        "\"revision\":1,\"restoredFromVersionToken\"",
                        "\"revision\":01,\"restoredFromVersionToken\"");
                    break;
                case "negative_zero":
                    json = json.Replace("\"createdAtUtcMs\":0", "\"createdAtUtcMs\":-0");
                    break;
                case "floating_point":
                    json = json.Replace(
                        "\"revision\":1,\"restoredFromVersionToken\"",
                        "\"revision\":1.0,\"restoredFromVersionToken\"");
                    break;
                case "scientific_notation":
                    json = json.Replace(
                        "\"revision\":1,\"restoredFromVersionToken\"",
                        "\"revision\":1e0,\"restoredFromVersionToken\"");
                    break;
                case "plus_sign":
                    json = json.Replace(
                        "\"revision\":1,\"restoredFromVersionToken\"",
                        "\"revision\":+1,\"restoredFromVersionToken\"");
                    break;
                case "too_large":
                    json = json.Replace("9007199254740991", "9007199254740992");
                    break;
                case "too_small":
                    json = json.Replace(
                        "\"revision\":1,\"restoredFromVersionToken\"",
                        "\"revision\":-9007199254740992,\"restoredFromVersionToken\"");
                    break;
                case "trailing_token":
                    json += "{}";
                    break;
                case "lone_surrogate":
                    json = json.Replace(
                        "\"displayName\":\"Player 雪" + char.ConvertFromUtf32(0x1f600) + "\"",
                        "\"displayName\":\"\\ud800\"");
                    break;
                case "raw_control":
                    json = json.Replace("\\u0000", "\0");
                    break;
                case "whitespace":
                    json = "{ " + json.Substring(1);
                    break;
                case "property_order":
                    json = json.Replace(
                        "\"schemaVersion\":2,\"contentVersion\":1",
                        "\"contentVersion\":1,\"schemaVersion\":2");
                    break;
                case "escaped_slash":
                    json = json.Replace("/ Controls", "\\/ Controls");
                    break;
                case "uppercase_unicode_escape":
                    json = json.Replace("\\u000b", "\\u000B");
                    break;
                case "long_control_escape":
                    json = json.Replace("\\b\\t\\n", "\\u0008\\u0009\\u000a");
                    break;
                case "noncanonical_unicode_escape":
                    json = json.Replace("Player 雪", "Player \\u96ea");
                    break;
                case "noncanonical_surrogate_escape":
                    json = json.Replace(
                        char.ConvertFromUtf32(0x1f600),
                        "\\ud83d\\ude00");
                    break;
                case "tampered_value":
                    json = json.Replace("Player 雪", "Player 霜");
                    break;
                case "missing_hash":
                    json = json.Replace(
                        "\"snapshotHash\":\"" + V2GoldenHash + "\"",
                        "\"notSnapshotHash\":\"" + V2GoldenHash + "\"");
                    break;
                default:
                    throw new AssertionException("Unknown mutation: " + mutation);
            }

            Assert.That(
                () => CareerSaveJsonCodec.Deserialize(Encoding.UTF8.GetBytes(json)),
                Throws.TypeOf<FormatException>());
        }

        [Test]
        public void Deserialize_RejectsInvalidUtf8AndBom()
        {
            Assert.That(
                () => CareerSaveJsonCodec.Deserialize(
                    new byte[] { 0x7b, 0x22, 0xc3, 0x28, 0x22, 0x7d }),
                Throws.TypeOf<FormatException>());

            var canonical = Convert.FromBase64String(V2GoldenBase64);
            var withBom = new byte[canonical.Length + 3];
            withBom[0] = 0xef;
            withBom[1] = 0xbb;
            withBom[2] = 0xbf;
            Buffer.BlockCopy(canonical, 0, withBom, 3, canonical.Length);
            Assert.That(
                () => CareerSaveJsonCodec.Deserialize(withBom),
                Throws.TypeOf<FormatException>());
        }

        private static CareerSaveSnapshot CreateGoldenCandidate(
            char storedHashCharacter = '0',
            string careerName = null)
        {
            var lineageId = new LineageId(GuidValue(3));
            var onboarding = new TryoutOnboardingState(
                new[]
                {
                    UnconfirmedStage(1),
                    UnconfirmedStage(2),
                    UnconfirmedStage(3)
                },
                1,
                false);
            var receipt = new OperationReceipt(
                new OperationId(GuidValue(200)),
                OperationKind.CreateCareer,
                OperationReceiptTarget.ForCreateCareer(),
                Digest('a'),
                lineageId,
                1,
                MaximumIJsonSafeInteger,
                OperationOutcomeKind.CareerCreated,
                OperationOutcomeSummary.ForCareerCreated());

            return new CareerSaveSnapshot(
                CareerSaveVersions.Current,
                new CareerSaveIdentity(
                    new ProfileId(GuidValue(1)),
                    new SaveId(GuidValue(2)),
                    lineageId,
                    1,
                    0,
                    MaximumIJsonSafeInteger,
                    Digest(storedHashCharacter)),
                CareerSeed.Parse(SeedHex()),
                careerName ?? SpecialCareerName(),
                new CareerPlayerDraft(
                    new PlayerId("player.alpha"),
                    "Player 雪" + char.ConvertFromUtf32(0x1f600),
                    12),
                onboarding,
                CareerProgressionState.Created(),
                TrainingEmphasisLedger.Empty,
                null,
                null,
                null,
                null,
                null,
                null,
                new[] { receipt });
        }

        private static string ComputeDocumentHash(CareerSaveDocumentV2 document)
        {
            var method = typeof(CareerSaveJsonCodec).GetMethod(
                "ComputeDocumentHash",
                BindingFlags.NonPublic | BindingFlags.Static);
            Assert.That(method, Is.Not.Null);
            return (string)method.Invoke(null, new object[] { document });
        }

        private static CareerSaveSnapshot CreateExecutedGoldenCandidate(string firstContentId)
        {
            return CreateFullCandidate(true, firstContentId);
        }

        private static CareerSaveSnapshot CreateFullCandidate(
            bool eventAlreadyResolved,
            string firstContentId = null)
        {
            var lineageId = new LineageId(GuidValue(3));
            var stages = new[] { ConfirmedStage(1), ConfirmedStage(2), ConfirmedStage(3) };
            var onboarding = new TryoutOnboardingState(stages, 0, true);
            var plan = new CareerWeekPlanState(
                new WeekPlanId(GuidValue(10)),
                1,
                2,
                new[]
                {
                    firstContentId == null
                        ? Action(11, 41, CareerWeekActionKind.TeamPractice)
                        : Action(
                            11,
                            41,
                            CareerWeekActionKind.SpecializedTraining,
                            firstContentId),
                    Action(12, 42, CareerWeekActionKind.Rest),
                    Action(13, 43, CareerWeekActionKind.Match)
                },
                true);
            var pendingEvent = PendingEvent(plan);
            var progression = eventAlreadyResolved
                ? CareerProgressionState.Planned(plan, 2)
                : CareerProgressionState.AwaitingEventChoice(plan, pendingEvent);

            var receipts = new List<OperationReceipt>
            {
                Receipt(
                    200,
                    1,
                    OperationKind.CreateCareer,
                    OperationReceiptTarget.ForCreateCareer(),
                    OperationOutcomeSummary.ForCareerCreated(),
                    lineageId)
            };
            for (var index = 0; index < stages.Length; index++)
            {
                var stage = stages[index];
                receipts.Add(
                    Receipt(
                        201 + index,
                        2 + index,
                        OperationKind.ConfirmTryoutStage,
                        OperationReceiptTarget.ForTryoutStage(
                            stage.StageNumber,
                            stage.OccurrenceId,
                            stage.ChoiceId),
                        OperationOutcomeSummary.ForTryoutAdvanced(
                            stage.ResolvedOutputs),
                        lineageId));
            }

            receipts.Add(
                Receipt(
                    210,
                    5,
                    OperationKind.ConfirmWeekPlan,
                    OperationReceiptTarget.ForWeekPlanConfirmation(plan.PlanId),
                    OperationOutcomeSummary.ForWeekPlanConfirmed(),
                    lineageId));
            receipts.Add(
                Receipt(
                    211,
                    6,
                    OperationKind.ExecuteWeekAction,
                    OperationReceiptTarget.ForWeekAction(
                        plan.PlanId,
                        plan.Slots[0].SlotActionId,
                        plan.Slots[0].OccurrenceId),
                    OperationOutcomeSummary.ForSlotCompleted(
                        Growth(1),
                        4,
                        1,
                        2),
                    lineageId));
            if (eventAlreadyResolved)
            {
                receipts.Add(
                    Receipt(
                        212,
                        7,
                        OperationKind.ResolveEventChoice,
                        OperationReceiptTarget.ForEventChoice(
                            plan.PlanId,
                            plan.Slots[0].SlotActionId,
                            plan.Slots[0].OccurrenceId,
                            pendingEvent.OccurrenceId,
                            pendingEvent.Options[0].OptionId),
                        OperationOutcomeSummary.ForEventChoiceApplied(
                            Growth(10),
                            5,
                            10,
                            -2),
                        lineageId));
            }

            var revision = eventAlreadyResolved ? 7 : 6;
            var trainingEmphases = firstContentId == null
                ? TrainingEmphasisLedger.Empty
                : TrainingEmphasisLedger.Empty.AddExecutedTraining(
                    plan.Slots[0],
                    CareerWeekActionCatalogV1.Create());
            return new CareerSaveSnapshot(
                CareerSaveVersions.Current,
                new CareerSaveIdentity(
                    new ProfileId(GuidValue(1)),
                    new SaveId(GuidValue(2)),
                    lineageId,
                    revision,
                    1000,
                    2000,
                    Digest('0'),
                    new CareerVersionToken(
                        new LineageId(GuidValue(4)),
                        1,
                        Digest('b'))),
                CareerSeed.Parse(SeedHex()),
                "Road to V League",
                new CareerPlayerDraft(new PlayerId("player.alpha"), "Lin", 12),
                onboarding,
                progression,
                trainingEmphases,
                Player(),
                new TeamId("team.university-a"),
                PotentialGrade.B,
                23,
                72,
                61,
                receipts);
        }

        private static TryoutStageState ConfirmedStage(int stage)
        {
            return new TryoutStageState(
                stage,
                new OccurrenceId(GuidValue(100 + stage)),
                1,
                "stage-" + stage + "-choice",
                new[]
                {
                    new TryoutResolvedOutput("stage-" + stage + "-primary", 10),
                    new TryoutResolvedOutput("stage-" + stage + "-secondary", -5)
                });
        }

        private static TryoutStageState UnconfirmedStage(int stage)
        {
            return new TryoutStageState(
                stage,
                new OccurrenceId(GuidValue(100 + stage)),
                1,
                null,
                Array.Empty<TryoutResolvedOutput>());
        }

        private static CareerWeekActionState Action(
            int actionId,
            int occurrenceId,
            CareerWeekActionKind kind)
        {
            return Action(actionId, occurrenceId, kind, ContentIdFor(kind));
        }

        private static CareerWeekActionState Action(
            int actionId,
            int occurrenceId,
            CareerWeekActionKind kind,
            string contentId)
        {
            return new CareerWeekActionState(
                new SlotActionId(GuidValue(actionId)),
                new OccurrenceId(GuidValue(occurrenceId)),
                kind,
                contentId);
        }

        private static string ContentIdFor(CareerWeekActionKind kind)
        {
            switch (kind)
            {
                case CareerWeekActionKind.SpecializedTraining: return "week_action.specialized.spike";
                case CareerWeekActionKind.StrengthTraining: return "week_action.strength.jump";
                case CareerWeekActionKind.TeamPractice: return "week_action.team_practice.standard";
                case CareerWeekActionKind.Rest: return "week_action.rest.standard";
                case CareerWeekActionKind.Match: return "schedule.u1w1.match.01";
                default: throw new ArgumentOutOfRangeException(nameof(kind));
            }
        }

        private static PendingCareerEvent PendingEvent(CareerWeekPlanState plan)
        {
            return new PendingCareerEvent(
                plan.PlanId,
                plan.Slots[0].SlotActionId,
                plan.Slots[0].OccurrenceId,
                "social.first-week",
                new OccurrenceId(GuidValue(50)),
                1,
                new CareerEventOptionEffect("accept", Growth(10), 5, 10, -2),
                new CareerEventOptionEffect("decline", Growth(1), -5, -10, 2));
        }

        private static CareerAttributeGrowthDelta Growth(long start)
        {
            return new CareerAttributeGrowthDelta(
                start,
                start + 10,
                start + 20,
                start + 30,
                start + 40,
                start + 50,
                start + 60,
                start + 70);
        }

        private static CareerPlayerRecord Player()
        {
            return new CareerPlayerRecord(
                new PlayerId("player.alpha"),
                "Lin",
                12,
                new CareerPlayerAttributes(
                    new CareerAttributeProgress(5100, 101),
                    new CareerAttributeProgress(5200, 102),
                    new CareerAttributeProgress(5300, 103),
                    new CareerAttributeProgress(5400, 104),
                    new CareerAttributeProgress(5500, 105),
                    new CareerAttributeProgress(5600, 106),
                    new CareerAttributeProgress(5700, 107),
                    new CareerAttributeProgress(5800, 108)));
        }

        private static OperationReceipt Receipt(
            int id,
            long revision,
            OperationKind operationKind,
            OperationReceiptTarget target,
            OperationOutcomeSummary outcomeSummary,
            LineageId lineageId)
        {
            return new OperationReceipt(
                new OperationId(GuidValue(id)),
                operationKind,
                target,
                Digest((char)('a' + (id % 6))),
                lineageId,
                revision,
                3000 + id,
                OutcomeKind(operationKind),
                outcomeSummary);
        }

        private static OperationOutcomeKind OutcomeKind(OperationKind kind)
        {
            switch (kind)
            {
                case OperationKind.CreateCareer:
                    return OperationOutcomeKind.CareerCreated;
                case OperationKind.ConfirmTryoutStage:
                    return OperationOutcomeKind.TryoutAdvanced;
                case OperationKind.ConfirmWeekPlan:
                    return OperationOutcomeKind.WeekPlanConfirmed;
                case OperationKind.ExecuteWeekAction:
                    return OperationOutcomeKind.SlotCompleted;
                case OperationKind.ResolveEventChoice:
                    return OperationOutcomeKind.EventChoiceApplied;
                default:
                    throw new ArgumentOutOfRangeException(nameof(kind), kind, null);
            }
        }

        private static string SpecialCareerName()
        {
            var builder = new StringBuilder("Escapes:\"\\/ Controls:");
            for (var value = 0; value < 32; value++)
            {
                builder.Append((char)value);
            }

            builder.Append(" Unicode:雪");
            builder.Append(char.ConvertFromUtf32(0x1f600));
            builder.Append(" é e\u0301");
            return builder.ToString();
        }

        private static string SeedHex()
        {
            return "000102030405060708090a0b0c0d0e0f" +
                   "101112131415161718191a1b1c1d1e1f";
        }

        private static Sha256Digest Digest(char value)
        {
            return new Sha256Digest(new string(value, 64));
        }

        private static Guid GuidValue(int value)
        {
            return Guid.Parse("00000000-0000-0000-0000-" + value.ToString("D12"));
        }
    }
}
